// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/agent.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_COMMON_AGENT_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_COMMON_AGENT_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "common/agent.pb.h"
#include "model/common/agent.gen.h"

namespace music_lyric_model::internal {
	inline lyric::common::AgentType toPb(music_lyric_model::common::AgentType value) {
		switch (value) {
		case music_lyric_model::common::AgentType::Unknown:
			return lyric::common::AGENT_TYPE_UNKNOWN;
		case music_lyric_model::common::AgentType::Person:
			return lyric::common::AGENT_TYPE_PERSON;
		case music_lyric_model::common::AgentType::Group:
			return lyric::common::AGENT_TYPE_GROUP;
		case music_lyric_model::common::AgentType::Other:
			return lyric::common::AGENT_TYPE_OTHER;
		case music_lyric_model::common::AgentType::Unspecified:
		default:
			return lyric::common::AGENT_TYPE_UNSPECIFIED;
		}
	}

	inline music_lyric_model::common::AgentType fromPb(lyric::common::AgentType value) {
		switch (value) {
		case lyric::common::AGENT_TYPE_UNKNOWN:
			return music_lyric_model::common::AgentType::Unknown;
		case lyric::common::AGENT_TYPE_PERSON:
			return music_lyric_model::common::AgentType::Person;
		case lyric::common::AGENT_TYPE_GROUP:
			return music_lyric_model::common::AgentType::Group;
		case lyric::common::AGENT_TYPE_OTHER:
			return music_lyric_model::common::AgentType::Other;
		case lyric::common::AGENT_TYPE_UNSPECIFIED:
		default:
			return music_lyric_model::common::AgentType::Unspecified;
		}
	}

	inline lyric::common::AgentItem toPb(const music_lyric_model::common::AgentItem& in) {
		lyric::common::AgentItem out;
		out.set_id(in.id);
		out.set_type(toPb(in.type));
		for (const auto& item : in.names) {
			out.add_names(item);
		}
		return out;
	}

	inline music_lyric_model::common::AgentItem fromPb(const lyric::common::AgentItem& in) {
		music_lyric_model::common::AgentItem out;
		out.id = in.id();
		out.type = fromPb(in.type());
		out.names.assign(in.names().begin(), in.names().end());
		return out;
	}
} // namespace music_lyric_model::internal

#endif
