// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/line.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_COMMON_LINE_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_COMMON_LINE_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "bridge/common/unknown.gen.h"
#include "common/line.pb.h"
#include "common/unknown.pb.h"
#include "model/common/line.gen.h"
#include "model/common/unknown.gen.h"

namespace music_lyric_model::internal {
	inline lyric::common::LineAnnotationRoman toPb(const music_lyric_model::common::LineAnnotationRoman& in) {
		lyric::common::LineAnnotationRoman out;
		if (in.language.has_value()) {
			out.set_language(*in.language);
		}
		out.set_content(in.content);
		return out;
	}

	inline music_lyric_model::common::LineAnnotationRoman fromPb(const lyric::common::LineAnnotationRoman& in) {
		music_lyric_model::common::LineAnnotationRoman out;
		if (in.has_language()) {
			out.language = in.language();
		}
		out.content = in.content();
		return out;
	}

	inline lyric::common::LineAnnotationTranslation toPb(const music_lyric_model::common::LineAnnotationTranslation& in) {
		lyric::common::LineAnnotationTranslation out;
		if (in.language.has_value()) {
			out.set_language(*in.language);
		}
		out.set_content(in.content);
		return out;
	}

	inline music_lyric_model::common::LineAnnotationTranslation fromPb(const lyric::common::LineAnnotationTranslation& in) {
		music_lyric_model::common::LineAnnotationTranslation out;
		if (in.has_language()) {
			out.language = in.language();
		}
		out.content = in.content();
		return out;
	}

	inline lyric::common::LineAnnotation toPb(const music_lyric_model::common::LineAnnotation& in) {
		lyric::common::LineAnnotation out;
		for (const auto& item : in.unknowns) {
			*out.add_unknowns() = toPb(item);
		}
		for (const auto& item : in.romans) {
			*out.add_romans() = toPb(item);
		}
		for (const auto& item : in.translations) {
			*out.add_translations() = toPb(item);
		}
		return out;
	}

	inline music_lyric_model::common::LineAnnotation fromPb(const lyric::common::LineAnnotation& in) {
		music_lyric_model::common::LineAnnotation out;
		out.unknowns.reserve(static_cast<size_t>(in.unknowns_size()));
		for (const auto& item : in.unknowns()) {
			out.unknowns.push_back(fromPb(item));
		}
		out.romans.reserve(static_cast<size_t>(in.romans_size()));
		for (const auto& item : in.romans()) {
			out.romans.push_back(fromPb(item));
		}
		out.translations.reserve(static_cast<size_t>(in.translations_size()));
		for (const auto& item : in.translations()) {
			out.translations.push_back(fromPb(item));
		}
		return out;
	}
} // namespace music_lyric_model::internal

#endif
