// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/meta.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_COMMON_META_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_COMMON_META_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "bridge/common/unknown.gen.h"
#include "common/meta.pb.h"
#include "common/unknown.pb.h"
#include "model/common/meta.gen.h"
#include "model/common/unknown.gen.h"

namespace music_lyric_model::internal {
	inline lyric::common::MetaText toPb(const music_lyric_model::common::MetaText& in) {
		lyric::common::MetaText out;
		if (in.language.has_value()) {
			out.set_language(*in.language);
		}
		out.set_content(in.content);
		return out;
	}

	inline music_lyric_model::common::MetaText fromPb(const lyric::common::MetaText& in) {
		music_lyric_model::common::MetaText out;
		if (in.has_language()) {
			out.language = in.language();
		}
		out.content = in.content();
		return out;
	}

	inline lyric::common::MetaCredit toPb(const music_lyric_model::common::MetaCredit& in) {
		lyric::common::MetaCredit out;
		out.set_role(in.role);
		for (const auto& item : in.names) {
			*out.add_names() = toPb(item);
		}
		return out;
	}

	inline music_lyric_model::common::MetaCredit fromPb(const lyric::common::MetaCredit& in) {
		music_lyric_model::common::MetaCredit out;
		out.role = in.role();
		out.names.reserve(static_cast<size_t>(in.names_size()));
		for (const auto& item : in.names()) {
			out.names.push_back(fromPb(item));
		}
		return out;
	}

	inline lyric::common::MetaReference toPb(const music_lyric_model::common::MetaReference& in) {
		lyric::common::MetaReference out;
		out.set_platform(in.platform);
		for (const auto& item : in.ids) {
			out.add_ids(item);
		}
		return out;
	}

	inline music_lyric_model::common::MetaReference fromPb(const lyric::common::MetaReference& in) {
		music_lyric_model::common::MetaReference out;
		out.platform = in.platform();
		out.ids.assign(in.ids().begin(), in.ids().end());
		return out;
	}

	inline lyric::common::Meta toPb(const music_lyric_model::common::Meta& in) {
		lyric::common::Meta out;
		for (const auto& item : in.unknowns) {
			*out.add_unknowns() = toPb(item);
		}
		out.set_offset(in.offset);
		out.set_duration(in.duration);
		for (const auto& item : in.titles) {
			*out.add_titles() = toPb(item);
		}
		for (const auto& item : in.artists) {
			*out.add_artists() = toPb(item);
		}
		for (const auto& item : in.albums) {
			*out.add_albums() = toPb(item);
		}
		for (const auto& item : in.authors) {
			*out.add_authors() = toPb(item);
		}
		for (const auto& item : in.isrcs) {
			out.add_isrcs(item);
		}
		for (const auto& item : in.credits) {
			*out.add_credits() = toPb(item);
		}
		for (const auto& item : in.references) {
			*out.add_references() = toPb(item);
		}
		return out;
	}

	inline music_lyric_model::common::Meta fromPb(const lyric::common::Meta& in) {
		music_lyric_model::common::Meta out;
		out.unknowns.reserve(static_cast<size_t>(in.unknowns_size()));
		for (const auto& item : in.unknowns()) {
			out.unknowns.push_back(fromPb(item));
		}
		out.offset = in.offset();
		out.duration = in.duration();
		out.titles.reserve(static_cast<size_t>(in.titles_size()));
		for (const auto& item : in.titles()) {
			out.titles.push_back(fromPb(item));
		}
		out.artists.reserve(static_cast<size_t>(in.artists_size()));
		for (const auto& item : in.artists()) {
			out.artists.push_back(fromPb(item));
		}
		out.albums.reserve(static_cast<size_t>(in.albums_size()));
		for (const auto& item : in.albums()) {
			out.albums.push_back(fromPb(item));
		}
		out.authors.reserve(static_cast<size_t>(in.authors_size()));
		for (const auto& item : in.authors()) {
			out.authors.push_back(fromPb(item));
		}
		out.isrcs.assign(in.isrcs().begin(), in.isrcs().end());
		out.credits.reserve(static_cast<size_t>(in.credits_size()));
		for (const auto& item : in.credits()) {
			out.credits.push_back(fromPb(item));
		}
		out.references.reserve(static_cast<size_t>(in.references_size()));
		for (const auto& item : in.references()) {
			out.references.push_back(fromPb(item));
		}
		return out;
	}
} // namespace music_lyric_model::internal

#endif
