// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/part.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_COMMON_PART_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_COMMON_PART_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "common/part.pb.h"
#include "model/common/part.gen.h"

namespace music_lyric_model::internal {
	inline lyric::common::PartType toPb(music_lyric_model::common::PartType value) {
		switch (value) {
		case music_lyric_model::common::PartType::Other:
			return lyric::common::PART_TYPE_OTHER;
		case music_lyric_model::common::PartType::Intro:
			return lyric::common::PART_TYPE_INTRO;
		case music_lyric_model::common::PartType::Verse:
			return lyric::common::PART_TYPE_VERSE;
		case music_lyric_model::common::PartType::PreChorus:
			return lyric::common::PART_TYPE_PRE_CHORUS;
		case music_lyric_model::common::PartType::Chorus:
			return lyric::common::PART_TYPE_CHORUS;
		case music_lyric_model::common::PartType::PostChorus:
			return lyric::common::PART_TYPE_POST_CHORUS;
		case music_lyric_model::common::PartType::Bridge:
			return lyric::common::PART_TYPE_BRIDGE;
		case music_lyric_model::common::PartType::Refrain:
			return lyric::common::PART_TYPE_REFRAIN;
		case music_lyric_model::common::PartType::Instrumental:
			return lyric::common::PART_TYPE_INSTRUMENTAL;
		case music_lyric_model::common::PartType::Outro:
			return lyric::common::PART_TYPE_OUTRO;
		case music_lyric_model::common::PartType::Unspecified:
		default:
			return lyric::common::PART_TYPE_UNSPECIFIED;
		}
	}

	inline music_lyric_model::common::PartType fromPb(lyric::common::PartType value) {
		switch (value) {
		case lyric::common::PART_TYPE_OTHER:
			return music_lyric_model::common::PartType::Other;
		case lyric::common::PART_TYPE_INTRO:
			return music_lyric_model::common::PartType::Intro;
		case lyric::common::PART_TYPE_VERSE:
			return music_lyric_model::common::PartType::Verse;
		case lyric::common::PART_TYPE_PRE_CHORUS:
			return music_lyric_model::common::PartType::PreChorus;
		case lyric::common::PART_TYPE_CHORUS:
			return music_lyric_model::common::PartType::Chorus;
		case lyric::common::PART_TYPE_POST_CHORUS:
			return music_lyric_model::common::PartType::PostChorus;
		case lyric::common::PART_TYPE_BRIDGE:
			return music_lyric_model::common::PartType::Bridge;
		case lyric::common::PART_TYPE_REFRAIN:
			return music_lyric_model::common::PartType::Refrain;
		case lyric::common::PART_TYPE_INSTRUMENTAL:
			return music_lyric_model::common::PartType::Instrumental;
		case lyric::common::PART_TYPE_OUTRO:
			return music_lyric_model::common::PartType::Outro;
		case lyric::common::PART_TYPE_UNSPECIFIED:
		default:
			return music_lyric_model::common::PartType::Unspecified;
		}
	}

	inline lyric::common::Part toPb(const music_lyric_model::common::Part& in) {
		lyric::common::Part out;
		out.set_type(toPb(in.type));
		if (in.label.has_value()) {
			out.set_label(*in.label);
		}
		return out;
	}

	inline music_lyric_model::common::Part fromPb(const lyric::common::Part& in) {
		music_lyric_model::common::Part out;
		out.type = fromPb(in.type());
		if (in.has_label()) {
			out.label = in.label();
		}
		return out;
	}
} // namespace music_lyric_model::internal

#endif
