// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/time.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_COMMON_TIME_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_COMMON_TIME_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "common/time.pb.h"
#include "model/common/time.gen.h"

namespace music_lyric_model::internal {
	inline lyric::common::Time toPb(const music_lyric_model::common::Time& in) {
		lyric::common::Time out;
		out.set_start(in.start);
		out.set_end(in.end);
		return out;
	}

	inline music_lyric_model::common::Time fromPb(const lyric::common::Time& in) {
		music_lyric_model::common::Time out;
		out.start = in.start();
		out.end = in.end();
		return out;
	}
} // namespace music_lyric_model::internal

#endif
