// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/timing.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_COMMON_TIMING_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_COMMON_TIMING_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "common/timing.pb.h"
#include "model/common/timing.gen.h"

namespace music_lyric_model::internal {
	inline lyric::common::Timing toPb(music_lyric_model::common::Timing value) {
		switch (value) {
		case music_lyric_model::common::Timing::None:
			return lyric::common::TIMING_NONE;
		case music_lyric_model::common::Timing::Line:
			return lyric::common::TIMING_LINE;
		case music_lyric_model::common::Timing::Word:
			return lyric::common::TIMING_WORD;
		case music_lyric_model::common::Timing::Unspecified:
		default:
			return lyric::common::TIMING_UNSPECIFIED;
		}
	}

	inline music_lyric_model::common::Timing fromPb(lyric::common::Timing value) {
		switch (value) {
		case lyric::common::TIMING_NONE:
			return music_lyric_model::common::Timing::None;
		case lyric::common::TIMING_LINE:
			return music_lyric_model::common::Timing::Line;
		case lyric::common::TIMING_WORD:
			return music_lyric_model::common::Timing::Word;
		case lyric::common::TIMING_UNSPECIFIED:
		default:
			return music_lyric_model::common::Timing::Unspecified;
		}
	}
} // namespace music_lyric_model::internal

#endif
