// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/unknown.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_COMMON_UNKNOWN_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_COMMON_UNKNOWN_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "common/unknown.pb.h"
#include "model/common/unknown.gen.h"

namespace music_lyric_model::internal {
	inline lyric::common::Unknown toPb(const music_lyric_model::common::Unknown& in) {
		lyric::common::Unknown out;
		out.set_key(in.key);
		out.set_value(in.value);
		return out;
	}

	inline music_lyric_model::common::Unknown fromPb(const lyric::common::Unknown& in) {
		music_lyric_model::common::Unknown out;
		out.key = in.key();
		out.value = in.value();
		return out;
	}
} // namespace music_lyric_model::internal

#endif
