// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/word.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_COMMON_WORD_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_COMMON_WORD_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "bridge/common/time.gen.h"
#include "bridge/common/unknown.gen.h"
#include "common/time.pb.h"
#include "common/unknown.pb.h"
#include "common/word.pb.h"
#include "model/common/time.gen.h"
#include "model/common/unknown.gen.h"
#include "model/common/word.gen.h"

namespace music_lyric_model::internal {
#ifndef MUSIC_LYRIC_MODEL_INTERNAL_MAP_HELPERS_
#define MUSIC_LYRIC_MODEL_INTERNAL_MAP_HELPERS_
	inline void putMap(const std::unordered_map<std::string, std::string>& src, google::protobuf::Map<std::string, std::string>* dst) {
		dst->clear();
		for (const auto& [k, v] : src) {
			(*dst)[k] = v;
		}
	}

	inline std::unordered_map<std::string, std::string> takeMap(const google::protobuf::Map<std::string, std::string>& src) {
		std::unordered_map<std::string, std::string> out;
		out.reserve(static_cast<size_t>(src.size()));
		for (const auto& [k, v] : src) {
			out.emplace(k, v);
		}
		return out;
	}
#endif // MUSIC_LYRIC_MODEL_INTERNAL_MAP_HELPERS_

	inline lyric::common::WordAnnotationContent toPb(const music_lyric_model::common::WordAnnotationContent& in) {
		lyric::common::WordAnnotationContent out;
		if (in.time.has_value()) {
			*out.mutable_time() = toPb(*in.time);
		}
		out.set_content(in.content);
		return out;
	}

	inline music_lyric_model::common::WordAnnotationContent fromPb(const lyric::common::WordAnnotationContent& in) {
		music_lyric_model::common::WordAnnotationContent out;
		if (in.has_time()) {
			out.time = fromPb(in.time());
		}
		out.content = in.content();
		return out;
	}

	inline lyric::common::WordAnnotationTranslation toPb(const music_lyric_model::common::WordAnnotationTranslation& in) {
		lyric::common::WordAnnotationTranslation out;
		if (in.language.has_value()) {
			out.set_language(*in.language);
		}
		out.set_content(in.content);
		return out;
	}

	inline music_lyric_model::common::WordAnnotationTranslation fromPb(const lyric::common::WordAnnotationTranslation& in) {
		music_lyric_model::common::WordAnnotationTranslation out;
		if (in.has_language()) {
			out.language = in.language();
		}
		out.content = in.content();
		return out;
	}

	inline lyric::common::WordAnnotationRoman toPb(const music_lyric_model::common::WordAnnotationRoman& in) {
		lyric::common::WordAnnotationRoman out;
		if (in.time.has_value()) {
			*out.mutable_time() = toPb(*in.time);
		}
		if (in.language.has_value()) {
			out.set_language(*in.language);
		}
		for (const auto& item : in.words) {
			*out.add_words() = toPb(item);
		}
		return out;
	}

	inline music_lyric_model::common::WordAnnotationRoman fromPb(const lyric::common::WordAnnotationRoman& in) {
		music_lyric_model::common::WordAnnotationRoman out;
		if (in.has_time()) {
			out.time = fromPb(in.time());
		}
		if (in.has_language()) {
			out.language = in.language();
		}
		out.words.reserve(static_cast<size_t>(in.words_size()));
		for (const auto& item : in.words()) {
			out.words.push_back(fromPb(item));
		}
		return out;
	}

	inline lyric::common::WordAnnotationRuby toPb(const music_lyric_model::common::WordAnnotationRuby& in) {
		lyric::common::WordAnnotationRuby out;
		if (in.time.has_value()) {
			*out.mutable_time() = toPb(*in.time);
		}
		if (in.language.has_value()) {
			out.set_language(*in.language);
		}
		for (const auto& item : in.words) {
			*out.add_words() = toPb(item);
		}
		out.set_phrase_start(in.phraseStart);
		return out;
	}

	inline music_lyric_model::common::WordAnnotationRuby fromPb(const lyric::common::WordAnnotationRuby& in) {
		music_lyric_model::common::WordAnnotationRuby out;
		if (in.has_time()) {
			out.time = fromPb(in.time());
		}
		if (in.has_language()) {
			out.language = in.language();
		}
		out.words.reserve(static_cast<size_t>(in.words_size()));
		for (const auto& item : in.words()) {
			out.words.push_back(fromPb(item));
		}
		out.phraseStart = in.phrase_start();
		return out;
	}

	inline lyric::common::WordAnnotation toPb(const music_lyric_model::common::WordAnnotation& in) {
		lyric::common::WordAnnotation out;
		for (const auto& item : in.unknowns) {
			*out.add_unknowns() = toPb(item);
		}
		for (const auto& item : in.rubies) {
			*out.add_rubies() = toPb(item);
		}
		for (const auto& item : in.romans) {
			*out.add_romans() = toPb(item);
		}
		for (const auto& item : in.translations) {
			*out.add_translations() = toPb(item);
		}
		return out;
	}

	inline music_lyric_model::common::WordAnnotation fromPb(const lyric::common::WordAnnotation& in) {
		music_lyric_model::common::WordAnnotation out;
		out.unknowns.reserve(static_cast<size_t>(in.unknowns_size()));
		for (const auto& item : in.unknowns()) {
			out.unknowns.push_back(fromPb(item));
		}
		out.rubies.reserve(static_cast<size_t>(in.rubies_size()));
		for (const auto& item : in.rubies()) {
			out.rubies.push_back(fromPb(item));
		}
		out.romans.reserve(static_cast<size_t>(in.romans_size()));
		for (const auto& item : in.romans()) {
			out.romans.push_back(fromPb(item));
		}
		out.translations.reserve(static_cast<size_t>(in.translations_size()));
		for (const auto& item : in.translations()) {
			out.translations.push_back(fromPb(item));
		}
		return out;
	}

	inline lyric::common::WordNormal toPb(const music_lyric_model::common::WordNormal& in) {
		lyric::common::WordNormal out;
		putMap(in.extra, out.mutable_extra());
		if (in.time.has_value()) {
			*out.mutable_time() = toPb(*in.time);
		}
		out.set_content(in.content);
		if (in.language.has_value()) {
			out.set_language(*in.language);
		}
		if (in.annotation.has_value()) {
			*out.mutable_annotation() = toPb(*in.annotation);
		}
		out.set_stress(in.stress);
		return out;
	}

	inline music_lyric_model::common::WordNormal fromPb(const lyric::common::WordNormal& in) {
		music_lyric_model::common::WordNormal out;
		out.extra = takeMap(in.extra());
		if (in.has_time()) {
			out.time = fromPb(in.time());
		}
		out.content = in.content();
		if (in.has_language()) {
			out.language = in.language();
		}
		if (in.has_annotation()) {
			out.annotation = fromPb(in.annotation());
		}
		out.stress = in.stress();
		return out;
	}

	inline lyric::common::WordSpace toPb(const music_lyric_model::common::WordSpace& in) {
		lyric::common::WordSpace out;
		out.set_count(in.count);
		return out;
	}

	inline music_lyric_model::common::WordSpace fromPb(const lyric::common::WordSpace& in) {
		music_lyric_model::common::WordSpace out;
		out.count = in.count();
		return out;
	}

	inline lyric::common::Word toPb(const music_lyric_model::common::Word& in) {
		lyric::common::Word out;
		if (const music_lyric_model::common::WordNormal* arm = std::get_if<music_lyric_model::common::WordNormal>(&in)) {
			*out.mutable_normal() = toPb(*arm);
			return out;
		}
		if (const music_lyric_model::common::WordSpace* arm = std::get_if<music_lyric_model::common::WordSpace>(&in)) {
			*out.mutable_space() = toPb(*arm);
			return out;
		}
		throw std::runtime_error("word body is unset");
	}

	inline music_lyric_model::common::Word fromPb(const lyric::common::Word& in) {
		switch (in.body_case()) {
		case lyric::common::Word::kNormal:
			return music_lyric_model::common::Word{fromPb(in.normal())};
		case lyric::common::Word::kSpace:
			return music_lyric_model::common::Word{fromPb(in.space())};
		case lyric::common::Word::BODY_NOT_SET:
		default:
			throw std::runtime_error("word body is unset");
		}
	}
} // namespace music_lyric_model::internal

#endif
