// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: parsed/language.proto

#ifndef MUSIC_LYRIC_MODEL_PARSED_LANGUAGE_GEN_H_
#define MUSIC_LYRIC_MODEL_PARSED_LANGUAGE_GEN_H_

#include <string>

namespace music_lyric_model::parsed {
	struct LanguageItem {
		/**
		 * BCP 47 language tag; unique within the list.
		 */
		std::string tag;
		/**
		 * Share within the lyric, ranging from 0 to 100, listed in descending order of percent.
		 * Computed from word-level language counts; values are approximate due to floating-point precision.
		 * Producers should normalize so that the sum of all items is approximately 100.
		 */
		double percent = 0;
	};
} // namespace music_lyric_model::parsed

#endif
