// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: parsed/line.proto

#ifndef MUSIC_LYRIC_MODEL_PARSED_LINE_GEN_H_
#define MUSIC_LYRIC_MODEL_PARSED_LINE_GEN_H_

#include <optional>
#include <string>
#include <unordered_map>
#include <variant>
#include <vector>

#include "model/common/line.gen.h"
#include "model/common/part.gen.h"
#include "model/common/time.gen.h"
#include "model/common/word.gen.h"

namespace music_lyric_model::parsed {
	/**
	 * Background vocal line attached to a normal line.
	 * Fields mirror storage.LineBackground (same names and order), plus `languages`.
	 */
	struct LineBackground {
		/**
		 * Line-level format-specific data with no typed field.
		 */
		std::unordered_map<std::string, std::string> extra;
		/**
		 * Time range of this background line.
		 */
		std::optional<music_lyric_model::common::Time> time;
		/**
		 * Identifiers of the performing agents.
		 * Multiple ids mean known agents performing together; a named ensemble should be a single GROUP agent instead.
		 */
		std::vector<std::string> agents;
		/**
		 * BCP 47 language tags of this line.
		 * A binding may fall back to the languages of its words when this is empty.
		 */
		std::vector<std::string> languages;
		/**
		 * Words composing the line in order.
		 */
		std::vector<music_lyric_model::common::Word> words;
		/**
		 * Annotations explicitly applied to the whole line.
		 * Aggregating word annotations into a line view is done by the binding at display time, not stored here.
		 */
		std::optional<music_lyric_model::common::LineAnnotation> annotation;
	};

	/**
	 * Primary lyric line.
	 * Fields mirror storage.Line (same names and order), plus `languages`.
	 */
	struct LineNormal {
		/**
		 * Line-level format-specific data with no typed field.
		 */
		std::unordered_map<std::string, std::string> extra;
		/**
		 * Time range of the line.
		 */
		std::optional<music_lyric_model::common::Time> time;
		/**
		 * Part this line belongs to.
		 */
		std::optional<music_lyric_model::common::Part> part;
		/**
		 * Identifiers of the performing agents.
		 * Multiple ids mean known agents performing together; a named ensemble should be a single GROUP agent instead.
		 */
		std::vector<std::string> agents;
		/**
		 * BCP 47 language tags of this line.
		 * A binding may fall back to the languages of its words when this is empty.
		 */
		std::vector<std::string> languages;
		/**
		 * Words composing the line in order.
		 */
		std::vector<music_lyric_model::common::Word> words;
		/**
		 * Annotations explicitly applied to the whole line.
		 * Aggregating word annotations into a line view is done by the binding at display time, not stored here.
		 */
		std::optional<music_lyric_model::common::LineAnnotation> annotation;
		/**
		 * Background lines attached to this line.
		 */
		std::vector<LineBackground> backgrounds;
	};

	/**
	 * An instrumental gap derived from the timeline after parsing; never persisted in the storage model.
	 */
	struct LineInterlude {
		/**
		 * Binding-specific data with no typed field, reserved for future use.
		 */
		std::unordered_map<std::string, std::string> extra;
		/**
		 * Time range of the interlude.
		 */
		std::optional<music_lyric_model::common::Time> time;
	};

	/**
	 * A lyric line; exactly one body variant must be set, an unset body is invalid.
	 */
	using Line = std::variant<LineNormal, LineInterlude>;
} // namespace music_lyric_model::parsed

#endif
