// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/agent.proto

#ifndef MUSIC_LYRIC_MODEL_COMMON_AGENT_GEN_H_
#define MUSIC_LYRIC_MODEL_COMMON_AGENT_GEN_H_

#include <string>
#include <vector>

namespace music_lyric_model::common {
	enum class AgentType {
		/**
		 * The type field was not set; treat as missing, not as a resolved kind.
		 */
		Unspecified = 0,
		/**
		 * The source named an agent kind that is not one of PERSON, GROUP, or OTHER.
		 * Distinct from UNSPECIFIED: the type was present but could not be mapped.
		 */
		Unknown = 1,
		/**
		 * A single person.
		 */
		Person = 2,
		/**
		 * A group of voices, such as a duet, harmony or chorus.
		 */
		Group = 3,
		/**
		 * Another kind of agent that is neither a person nor a group.
		 */
		Other = 4,
	};

	struct AgentItem {
		/**
		 * Unique identifier of the agent.
		 */
		std::string id;
		/**
		 * Performing type of the agent.
		 */
		AgentType type = AgentType::Unspecified;
		/**
		 * Display names of the agent; a group may carry more than one.
		 */
		std::vector<std::string> names;
	};
} // namespace music_lyric_model::common

#endif
