// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/line.proto

#ifndef MUSIC_LYRIC_MODEL_COMMON_LINE_GEN_H_
#define MUSIC_LYRIC_MODEL_COMMON_LINE_GEN_H_

#include <optional>
#include <string>
#include <vector>

#include "model/common/unknown.gen.h"

namespace music_lyric_model::common {
	struct LineAnnotationRoman {
		/**
		 * Language (BCP 47 tag) or transliteration scheme of this item.
		 */
		std::optional<std::string> language;
		/**
		 * Romanized text.
		 */
		std::string content;
	};

	struct LineAnnotationTranslation {
		/**
		 * Language (BCP 47 tag) or transliteration scheme of this item.
		 */
		std::optional<std::string> language;
		/**
		 * Translated text.
		 */
		std::string content;
	};

	/**
	 * Line-level annotations explicitly present in the source.
	 * Aggregations from word annotations are computed by the binding at display time and never stored here.
	 */
	struct LineAnnotation {
		/**
		 * Unknown annotations preserved by their original key.
		 */
		std::vector<Unknown> unknowns;
		/**
		 * Romanized transliteration.
		 */
		std::vector<LineAnnotationRoman> romans;
		/**
		 * Translation into another language.
		 */
		std::vector<LineAnnotationTranslation> translations;
	};
} // namespace music_lyric_model::common

#endif
