// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/meta.proto

#ifndef MUSIC_LYRIC_MODEL_COMMON_META_GEN_H_
#define MUSIC_LYRIC_MODEL_COMMON_META_GEN_H_

#include <cstdint>
#include <optional>
#include <string>
#include <vector>

#include "model/common/unknown.gen.h"

namespace music_lyric_model::common {
	struct MetaText {
		/**
		 * BCP 47 language tag of this content; unset means unspecified or default.
		 */
		std::optional<std::string> language;
		/**
		 * Text content.
		 */
		std::string content;
	};

	struct MetaCredit {
		/**
		 * Role of the credit, such as lyricist or composer.
		 */
		std::string role;
		/**
		 * Names credited for this role.
		 */
		std::vector<MetaText> names;
	};

	struct MetaReference {
		/**
		 * Platform name.
		 */
		std::string platform;
		/**
		 * Identifiers on that platform.
		 */
		std::vector<std::string> ids;
	};

	struct Meta {
		/**
		 * Unrecognized meta preserved by their original key.
		 */
		std::vector<Unknown> unknowns;
		/**
		 * Lyric time offset in milliseconds.
		 */
		int32_t offset = 0;
		/**
		 * Song duration in milliseconds.
		 */
		uint32_t duration = 0;
		/**
		 * Song titles.
		 */
		std::vector<MetaText> titles;
		/**
		 * Song artists.
		 */
		std::vector<MetaText> artists;
		/**
		 * Song albums.
		 */
		std::vector<MetaText> albums;
		/**
		 * Authors or transcribers of the lyric file, not the song itself.
		 */
		std::vector<MetaText> authors;
		/**
		 * International Standard Recording Codes.
		 */
		std::vector<std::string> isrcs;
		/**
		 * Song credits such as lyricist or composer.
		 */
		std::vector<MetaCredit> credits;
		/**
		 * Cross-platform references.
		 */
		std::vector<MetaReference> references;
	};
} // namespace music_lyric_model::common

#endif
