// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/part.proto

#ifndef MUSIC_LYRIC_MODEL_COMMON_PART_GEN_H_
#define MUSIC_LYRIC_MODEL_COMMON_PART_GEN_H_

#include <optional>
#include <string>

namespace music_lyric_model::common {
	enum class PartType {
		Unspecified = 0,
		/**
		 * A recognized but non-standard part type; the original name is kept in `Part.label`.
		 */
		Other = 1,
		/**
		 * Introductory section.
		 */
		Intro = 2,
		/**
		 * Verse.
		 */
		Verse = 3,
		/**
		 * Section leading into the chorus.
		 */
		PreChorus = 4,
		/**
		 * Chorus.
		 */
		Chorus = 5,
		/**
		 * Section following the chorus.
		 */
		PostChorus = 6,
		/**
		 * Bridge.
		 */
		Bridge = 7,
		/**
		 * Refrain.
		 */
		Refrain = 8,
		/**
		 * Instrumental section.
		 */
		Instrumental = 9,
		/**
		 * Closing section.
		 */
		Outro = 10,
	};

	struct Part {
		/**
		 * Structural type of the part.
		 */
		PartType type = PartType::Unspecified;
		/**
		 * Original or custom label, such as the source tag or a name for an OTHER part.
		 */
		std::optional<std::string> label;
	};
} // namespace music_lyric_model::common

#endif
