// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/time.proto

#ifndef MUSIC_LYRIC_MODEL_COMMON_TIME_GEN_H_
#define MUSIC_LYRIC_MODEL_COMMON_TIME_GEN_H_

#include <cstdint>

namespace music_lyric_model::common {
	struct Time {
		/**
		 * Start time in milliseconds.
		 */
		uint32_t start = 0;
		/**
		 * End time in milliseconds.
		 */
		uint32_t end = 0;
	};
} // namespace music_lyric_model::common

#endif
