// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/timing.proto

#ifndef MUSIC_LYRIC_MODEL_COMMON_TIMING_GEN_H_
#define MUSIC_LYRIC_MODEL_COMMON_TIMING_GEN_H_

namespace music_lyric_model::common {
	/**
	 * Declared timing precision for a lyric.
	 * Producers should fill Time fields to match; consumers may treat mismatches as best-effort.
	 */
	enum class Timing {
		Unspecified = 0,
		/**
		 * Untimed; the lyric carries no meaningful time.
		 * Line and word Time fields should be unset or zero.
		 */
		None = 1,
		/**
		 * Timed at line level.
		 * Each normal or background line should carry a valid Time; word-level Time is optional.
		 */
		Line = 2,
		/**
		 * Timed at word level.
		 * Each WordNormal should carry a valid Time; line Time should cover its words.
		 */
		Word = 3,
	};
} // namespace music_lyric_model::common

#endif
