// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/unknown.proto

#ifndef MUSIC_LYRIC_MODEL_COMMON_UNKNOWN_GEN_H_
#define MUSIC_LYRIC_MODEL_COMMON_UNKNOWN_GEN_H_

#include <string>

namespace music_lyric_model::common {
	struct Unknown {
		/**
		 * Original key under which the raw value was preserved.
		 */
		std::string key;
		/**
		 * Raw value.
		 */
		std::string value;
	};
} // namespace music_lyric_model::common

#endif
