// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: common/word.proto

#ifndef MUSIC_LYRIC_MODEL_COMMON_WORD_GEN_H_
#define MUSIC_LYRIC_MODEL_COMMON_WORD_GEN_H_

#include <cstdint>
#include <optional>
#include <string>
#include <unordered_map>
#include <variant>
#include <vector>

#include "model/common/time.gen.h"
#include "model/common/unknown.gen.h"

namespace music_lyric_model::common {
	struct WordAnnotationContent {
		/**
		 * Time range of the token.
		 */
		std::optional<Time> time;
		/**
		 * Text content of the token.
		 */
		std::string content;
	};

	struct WordAnnotationTranslation {
		/**
		 * Target language of this translation, as a BCP 47 tag.
		 * Set it when multiple languages coexist, to tell them apart.
		 */
		std::optional<std::string> language;
		/**
		 * Translated text for the whole word.
		 * Unlike roman or ruby, translation has no independent time axis and is not tokenized.
		 */
		std::string content;
	};

	struct WordAnnotationRoman {
		/**
		 * Time range of the item, independent from its words.
		 */
		std::optional<Time> time;
		/**
		 * Language (BCP 47 tag) or transliteration scheme of this item.
		 * Set it when multiple languages coexist, to tell them apart.
		 */
		std::optional<std::string> language;
		/**
		 * Tokens composing the item in order.
		 */
		std::vector<WordAnnotationContent> words;
	};

	struct WordAnnotationRuby {
		/**
		 * Time range of the item, independent from its words.
		 */
		std::optional<Time> time;
		/**
		 * Language (BCP 47 tag) or transliteration scheme of this item.
		 * Set it when multiple languages coexist, to tell them apart.
		 */
		std::optional<std::string> language;
		/**
		 * Tokens composing the item in order.
		 */
		std::vector<WordAnnotationContent> words;
		/**
		 * Whether this ruby begins a phrase; a phrase runs until the next
		 * ruby marked as a start, in document order across the line's words.
		 * Currently populated only from TTML; unset elsewhere.
		 */
		bool phraseStart = false;
	};

	struct WordAnnotation {
		/**
		 * Unknown annotations preserved by their original key.
		 */
		std::vector<Unknown> unknowns;
		/**
		 * Ruby annotations such as furigana.
		 */
		std::vector<WordAnnotationRuby> rubies;
		/**
		 * Romanized transliterations.
		 */
		std::vector<WordAnnotationRoman> romans;
		/**
		 * Translations into another language.
		 */
		std::vector<WordAnnotationTranslation> translations;
	};

	struct WordNormal {
		/**
		 * Word-level format-specific data with no typed field.
		 */
		std::unordered_map<std::string, std::string> extra;
		/**
		 * Time range of the word.
		 */
		std::optional<Time> time;
		/**
		 * Text content of the word.
		 * Inter-word separators are modeled as WordSpace tokens, not embedded here.
		 */
		std::string content;
		/**
		 * Language of this word, as a BCP 47 tag.
		 */
		std::optional<std::string> language;
		/**
		 * Annotations attached to this word.
		 */
		std::optional<WordAnnotation> annotation;
		/**
		 * Whether the word is stressed.
		 */
		bool stress = false;
	};

	struct WordSpace {
		/**
		 * Number of consecutive space characters.
		 */
		uint32_t count = 0;
	};

	/**
	 * A word token; exactly one body variant must be set, an unset body is invalid.
	 */
	using Word = std::variant<WordNormal, WordSpace>;
} // namespace music_lyric_model::common

#endif
