// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: parsed/info.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_PARSED_INFO_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_PARSED_INFO_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "bridge/common/agent.gen.h"
#include "bridge/common/meta.gen.h"
#include "bridge/common/timing.gen.h"
#include "bridge/parsed/language.gen.h"
#include "bridge/parsed/line.gen.h"
#include "common/agent.pb.h"
#include "common/meta.pb.h"
#include "common/timing.pb.h"
#include "model/common/agent.gen.h"
#include "model/common/meta.gen.h"
#include "model/common/timing.gen.h"
#include "model/parsed/info.gen.h"
#include "model/parsed/language.gen.h"
#include "model/parsed/line.gen.h"
#include "parsed/info.pb.h"
#include "parsed/language.pb.h"
#include "parsed/line.pb.h"

namespace music_lyric_model::internal {
#ifndef MUSIC_LYRIC_MODEL_INTERNAL_MAP_HELPERS_
#define MUSIC_LYRIC_MODEL_INTERNAL_MAP_HELPERS_
	inline void putMap(const std::unordered_map<std::string, std::string>& src, google::protobuf::Map<std::string, std::string>* dst) {
		dst->clear();
		for (const auto& [k, v] : src) {
			(*dst)[k] = v;
		}
	}

	inline std::unordered_map<std::string, std::string> takeMap(const google::protobuf::Map<std::string, std::string>& src) {
		std::unordered_map<std::string, std::string> out;
		out.reserve(static_cast<size_t>(src.size()));
		for (const auto& [k, v] : src) {
			out.emplace(k, v);
		}
		return out;
	}
#endif // MUSIC_LYRIC_MODEL_INTERNAL_MAP_HELPERS_

	inline lyric::parsed::InfoType toPb(music_lyric_model::parsed::InfoType value) {
		switch (value) {
		case music_lyric_model::parsed::InfoType::Invalid:
			return lyric::parsed::INFO_TYPE_INVALID;
		case music_lyric_model::parsed::InfoType::Valid:
			return lyric::parsed::INFO_TYPE_VALID;
		case music_lyric_model::parsed::InfoType::Unspecified:
		default:
			return lyric::parsed::INFO_TYPE_UNSPECIFIED;
		}
	}

	inline music_lyric_model::parsed::InfoType fromPb(lyric::parsed::InfoType value) {
		switch (value) {
		case lyric::parsed::INFO_TYPE_INVALID:
			return music_lyric_model::parsed::InfoType::Invalid;
		case lyric::parsed::INFO_TYPE_VALID:
			return music_lyric_model::parsed::InfoType::Valid;
		case lyric::parsed::INFO_TYPE_UNSPECIFIED:
		default:
			return music_lyric_model::parsed::InfoType::Unspecified;
		}
	}

	inline lyric::parsed::Info toPb(const music_lyric_model::parsed::Info& in) {
		lyric::parsed::Info out;
		out.set_version(in.version);
		out.set_type(toPb(in.type));
		out.set_timing(toPb(in.timing));
		putMap(in.extra, out.mutable_extra());
		*out.mutable_meta() = toPb(in.meta);
		for (const auto& item : in.languages) {
			*out.add_languages() = toPb(item);
		}
		for (const auto& item : in.agents) {
			*out.add_agents() = toPb(item);
		}
		for (const auto& item : in.lines) {
			*out.add_lines() = toPb(item);
		}
		return out;
	}

	inline music_lyric_model::parsed::Info fromPb(const lyric::parsed::Info& in) {
		music_lyric_model::parsed::Info out;
		out.version = in.version();
		out.type = fromPb(in.type());
		out.timing = fromPb(in.timing());
		out.extra = takeMap(in.extra());
		if (in.has_meta()) {
			out.meta = fromPb(in.meta());
		}
		out.languages.reserve(static_cast<size_t>(in.languages_size()));
		for (const auto& item : in.languages()) {
			out.languages.push_back(fromPb(item));
		}
		out.agents.reserve(static_cast<size_t>(in.agents_size()));
		for (const auto& item : in.agents()) {
			out.agents.push_back(fromPb(item));
		}
		out.lines.reserve(static_cast<size_t>(in.lines_size()));
		for (const auto& item : in.lines()) {
			out.lines.push_back(fromPb(item));
		}
		return out;
	}
} // namespace music_lyric_model::internal

#endif
