// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: parsed/language.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_PARSED_LANGUAGE_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_PARSED_LANGUAGE_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "model/parsed/language.gen.h"
#include "parsed/language.pb.h"

namespace music_lyric_model::internal {
	inline lyric::parsed::LanguageItem toPb(const music_lyric_model::parsed::LanguageItem& in) {
		lyric::parsed::LanguageItem out;
		out.set_tag(in.tag);
		out.set_percent(in.percent);
		return out;
	}

	inline music_lyric_model::parsed::LanguageItem fromPb(const lyric::parsed::LanguageItem& in) {
		music_lyric_model::parsed::LanguageItem out;
		out.tag = in.tag();
		out.percent = in.percent();
		return out;
	}
} // namespace music_lyric_model::internal

#endif
