// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: parsed/line.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_PARSED_LINE_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_PARSED_LINE_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "bridge/common/line.gen.h"
#include "bridge/common/part.gen.h"
#include "bridge/common/time.gen.h"
#include "bridge/common/word.gen.h"
#include "common/line.pb.h"
#include "common/part.pb.h"
#include "common/time.pb.h"
#include "common/word.pb.h"
#include "model/common/line.gen.h"
#include "model/common/part.gen.h"
#include "model/common/time.gen.h"
#include "model/common/word.gen.h"
#include "model/parsed/line.gen.h"
#include "parsed/line.pb.h"

namespace music_lyric_model::internal {
#ifndef MUSIC_LYRIC_MODEL_INTERNAL_MAP_HELPERS_
#define MUSIC_LYRIC_MODEL_INTERNAL_MAP_HELPERS_
	inline void putMap(const std::unordered_map<std::string, std::string>& src, google::protobuf::Map<std::string, std::string>* dst) {
		dst->clear();
		for (const auto& [k, v] : src) {
			(*dst)[k] = v;
		}
	}

	inline std::unordered_map<std::string, std::string> takeMap(const google::protobuf::Map<std::string, std::string>& src) {
		std::unordered_map<std::string, std::string> out;
		out.reserve(static_cast<size_t>(src.size()));
		for (const auto& [k, v] : src) {
			out.emplace(k, v);
		}
		return out;
	}
#endif // MUSIC_LYRIC_MODEL_INTERNAL_MAP_HELPERS_

	inline lyric::parsed::LineBackground toPb(const music_lyric_model::parsed::LineBackground& in) {
		lyric::parsed::LineBackground out;
		putMap(in.extra, out.mutable_extra());
		if (in.time.has_value()) {
			*out.mutable_time() = toPb(*in.time);
		}
		for (const auto& item : in.agents) {
			out.add_agents(item);
		}
		for (const auto& item : in.languages) {
			out.add_languages(item);
		}
		for (const auto& item : in.words) {
			*out.add_words() = toPb(item);
		}
		if (in.annotation.has_value()) {
			*out.mutable_annotation() = toPb(*in.annotation);
		}
		return out;
	}

	inline music_lyric_model::parsed::LineBackground fromPb(const lyric::parsed::LineBackground& in) {
		music_lyric_model::parsed::LineBackground out;
		out.extra = takeMap(in.extra());
		if (in.has_time()) {
			out.time = fromPb(in.time());
		}
		out.agents.assign(in.agents().begin(), in.agents().end());
		out.languages.assign(in.languages().begin(), in.languages().end());
		out.words.reserve(static_cast<size_t>(in.words_size()));
		for (const auto& item : in.words()) {
			out.words.push_back(fromPb(item));
		}
		if (in.has_annotation()) {
			out.annotation = fromPb(in.annotation());
		}
		return out;
	}

	inline lyric::parsed::LineNormal toPb(const music_lyric_model::parsed::LineNormal& in) {
		lyric::parsed::LineNormal out;
		putMap(in.extra, out.mutable_extra());
		if (in.time.has_value()) {
			*out.mutable_time() = toPb(*in.time);
		}
		if (in.part.has_value()) {
			*out.mutable_part() = toPb(*in.part);
		}
		for (const auto& item : in.agents) {
			out.add_agents(item);
		}
		for (const auto& item : in.languages) {
			out.add_languages(item);
		}
		for (const auto& item : in.words) {
			*out.add_words() = toPb(item);
		}
		if (in.annotation.has_value()) {
			*out.mutable_annotation() = toPb(*in.annotation);
		}
		for (const auto& item : in.backgrounds) {
			*out.add_backgrounds() = toPb(item);
		}
		return out;
	}

	inline music_lyric_model::parsed::LineNormal fromPb(const lyric::parsed::LineNormal& in) {
		music_lyric_model::parsed::LineNormal out;
		out.extra = takeMap(in.extra());
		if (in.has_time()) {
			out.time = fromPb(in.time());
		}
		if (in.has_part()) {
			out.part = fromPb(in.part());
		}
		out.agents.assign(in.agents().begin(), in.agents().end());
		out.languages.assign(in.languages().begin(), in.languages().end());
		out.words.reserve(static_cast<size_t>(in.words_size()));
		for (const auto& item : in.words()) {
			out.words.push_back(fromPb(item));
		}
		if (in.has_annotation()) {
			out.annotation = fromPb(in.annotation());
		}
		out.backgrounds.reserve(static_cast<size_t>(in.backgrounds_size()));
		for (const auto& item : in.backgrounds()) {
			out.backgrounds.push_back(fromPb(item));
		}
		return out;
	}

	inline lyric::parsed::LineInterlude toPb(const music_lyric_model::parsed::LineInterlude& in) {
		lyric::parsed::LineInterlude out;
		putMap(in.extra, out.mutable_extra());
		if (in.time.has_value()) {
			*out.mutable_time() = toPb(*in.time);
		}
		return out;
	}

	inline music_lyric_model::parsed::LineInterlude fromPb(const lyric::parsed::LineInterlude& in) {
		music_lyric_model::parsed::LineInterlude out;
		out.extra = takeMap(in.extra());
		if (in.has_time()) {
			out.time = fromPb(in.time());
		}
		return out;
	}

	inline lyric::parsed::Line toPb(const music_lyric_model::parsed::Line& in) {
		lyric::parsed::Line out;
		if (const music_lyric_model::parsed::LineNormal* arm = std::get_if<music_lyric_model::parsed::LineNormal>(&in)) {
			*out.mutable_normal() = toPb(*arm);
			return out;
		}
		if (const music_lyric_model::parsed::LineInterlude* arm = std::get_if<music_lyric_model::parsed::LineInterlude>(&in)) {
			*out.mutable_interlude() = toPb(*arm);
			return out;
		}
		throw std::runtime_error("line body is unset");
	}

	inline music_lyric_model::parsed::Line fromPb(const lyric::parsed::Line& in) {
		switch (in.body_case()) {
		case lyric::parsed::Line::kNormal:
			return music_lyric_model::parsed::Line{fromPb(in.normal())};
		case lyric::parsed::Line::kInterlude:
			return music_lyric_model::parsed::Line{fromPb(in.interlude())};
		case lyric::parsed::Line::BODY_NOT_SET:
		default:
			throw std::runtime_error("line body is unset");
		}
	}
} // namespace music_lyric_model::internal

#endif
