// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: storage/lyric.proto

#ifndef MUSIC_LYRIC_MODEL_INTERNAL_STORAGE_LYRIC_BRIDGE_H_
#define MUSIC_LYRIC_MODEL_INTERNAL_STORAGE_LYRIC_BRIDGE_H_

// Internal protobuf bridging. Not part of the public API.

#include <optional>
#include <stdexcept>
#include <string>
#include <unordered_map>
#include <utility>
#include <variant>
#include <vector>

#include "bridge/common/agent.gen.h"
#include "bridge/common/meta.gen.h"
#include "bridge/common/timing.gen.h"
#include "bridge/storage/line.gen.h"
#include "common/agent.pb.h"
#include "common/meta.pb.h"
#include "common/timing.pb.h"
#include "model/common/agent.gen.h"
#include "model/common/meta.gen.h"
#include "model/common/timing.gen.h"
#include "model/storage/line.gen.h"
#include "model/storage/lyric.gen.h"
#include "storage/line.pb.h"
#include "storage/lyric.pb.h"

namespace music_lyric_model::internal {
	inline void putMap(const std::unordered_map<std::string, std::string>& src, google::protobuf::Map<std::string, std::string>* dst) {
		dst->clear();
		for (const auto& [k, v] : src) {
			(*dst)[k] = v;
		}
	}

	inline std::unordered_map<std::string, std::string> takeMap(const google::protobuf::Map<std::string, std::string>& src) {
		std::unordered_map<std::string, std::string> out;
		out.reserve(static_cast<size_t>(src.size()));
		for (const auto& [k, v] : src) {
			out.emplace(k, v);
		}
		return out;
	}

	inline lyric::storage::Lyric toPb(const music_lyric_model::storage::Lyric& in) {
		lyric::storage::Lyric out;
		out.set_version(in.version);
		out.set_timing(toPb(in.timing));
		putMap(in.extra, out.mutable_extra());
		*out.mutable_meta() = toPb(in.meta);
		for (const auto& item : in.agents) {
			*out.add_agents() = toPb(item);
		}
		for (const auto& item : in.lines) {
			*out.add_lines() = toPb(item);
		}
		return out;
	}

	inline music_lyric_model::storage::Lyric fromPb(const lyric::storage::Lyric& in) {
		music_lyric_model::storage::Lyric out;
		out.version = in.version();
		out.timing = fromPb(in.timing());
		out.extra = takeMap(in.extra());
		if (in.has_meta()) {
			out.meta = fromPb(in.meta());
		}
		out.agents.reserve(static_cast<size_t>(in.agents_size()));
		for (const auto& item : in.agents()) {
			out.agents.push_back(fromPb(item));
		}
		out.lines.reserve(static_cast<size_t>(in.lines_size()));
		for (const auto& item : in.lines()) {
			out.lines.push_back(fromPb(item));
		}
		return out;
	}
} // namespace music_lyric_model::internal

#endif
