// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage/line.proto
// Protobuf C++ Version: 7.35.1

#include "storage/line.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::lyric::storage::LineBackground_ExtraEntry_DoNotUse
        {&::_pbi::kDescriptorMethods, &::descriptor_table_storage_2fline_2eproto, /* tracker*/ nullptr,},
        // ::lyric::storage::LineBackground
        {&::_pbi::kDescriptorMethods, &::descriptor_table_storage_2fline_2eproto, /* tracker*/ nullptr,},
        // ::lyric::storage::Line_ExtraEntry_DoNotUse
        {&::_pbi::kDescriptorMethods, &::descriptor_table_storage_2fline_2eproto, /* tracker*/ nullptr,},
        // ::lyric::storage::Line
        {&::_pbi::kDescriptorMethods, &::descriptor_table_storage_2fline_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace lyric {
namespace storage {
constexpr LineBackground_ExtraEntry_DoNotUse::ParseTableT_ LineBackground_ExtraEntry_DoNotUse::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(LineBackground_ExtraEntry_DoNotUse, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::lyric::storage::LineBackground_ExtraEntry_DoNotUse>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string value = 2 [json_name = "value"];
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(LineBackground_ExtraEntry_DoNotUse, _impl_.value_)}},
      // string key = 1 [json_name = "key"];
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(LineBackground_ExtraEntry_DoNotUse, _impl_.key_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string key = 1 [json_name = "key"];
      {PROTOBUF_FIELD_OFFSET(LineBackground_ExtraEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string value = 2 [json_name = "value"];
      {PROTOBUF_FIELD_OFFSET(LineBackground_ExtraEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\47\3\5\0\0\0\0\0"
      "lyric.storage.LineBackground.ExtraEntry"
      "key"
      "value"
    }},
  };
}

template <typename>
constexpr LineBackground_ExtraEntry_DoNotUse::LineBackground_ExtraEntry_DoNotUse(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : LineBackground_ExtraEntry_DoNotUse::MapEntry(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL LineBackground_ExtraEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) LineBackground_ExtraEntry_DoNotUse(arena);
}
constexpr auto LineBackground_ExtraEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(LineBackground_ExtraEntry_DoNotUse), alignof(LineBackground_ExtraEntry_DoNotUse));
}
constexpr auto LineBackground_ExtraEntry_DoNotUse::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &LineBackground_ExtraEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<LineBackground_ExtraEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &LineBackground_ExtraEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&LineBackground_ExtraEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(LineBackground_ExtraEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_storage_2fline_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct LineBackground_ExtraEntry_DoNotUseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr LineBackground_ExtraEntry_DoNotUseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 LineBackground_ExtraEntry_DoNotUse_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(LineBackground_ExtraEntry_DoNotUse::InternalGenerateClassData_(
            _default, &LineBackground_ExtraEntry_DoNotUse_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<LineBackground_ExtraEntry_DoNotUse>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~LineBackground_ExtraEntry_DoNotUseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) LineBackground_ExtraEntry_DoNotUse _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<LineBackground_ExtraEntry_DoNotUse>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(LineBackground_ExtraEntry_DoNotUseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST LineBackground_ExtraEntry_DoNotUseGlobalsTypeInternal LineBackground_ExtraEntry_DoNotUse_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* LineBackground_ExtraEntry_DoNotUse_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return LineBackground_ExtraEntry_DoNotUse_globals_.GetClassData();
#else
  return LineBackground_ExtraEntry_DoNotUse_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
constexpr Line_ExtraEntry_DoNotUse::ParseTableT_ Line_ExtraEntry_DoNotUse::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(Line_ExtraEntry_DoNotUse, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::lyric::storage::Line_ExtraEntry_DoNotUse>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string value = 2 [json_name = "value"];
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(Line_ExtraEntry_DoNotUse, _impl_.value_)}},
      // string key = 1 [json_name = "key"];
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(Line_ExtraEntry_DoNotUse, _impl_.key_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string key = 1 [json_name = "key"];
      {PROTOBUF_FIELD_OFFSET(Line_ExtraEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string value = 2 [json_name = "value"];
      {PROTOBUF_FIELD_OFFSET(Line_ExtraEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\35\3\5\0\0\0\0\0"
      "lyric.storage.Line.ExtraEntry"
      "key"
      "value"
    }},
  };
}

template <typename>
constexpr Line_ExtraEntry_DoNotUse::Line_ExtraEntry_DoNotUse(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Line_ExtraEntry_DoNotUse::MapEntry(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL Line_ExtraEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Line_ExtraEntry_DoNotUse(arena);
}
constexpr auto Line_ExtraEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Line_ExtraEntry_DoNotUse), alignof(Line_ExtraEntry_DoNotUse));
}
constexpr auto Line_ExtraEntry_DoNotUse::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &Line_ExtraEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Line_ExtraEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Line_ExtraEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&Line_ExtraEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Line_ExtraEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[2],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_storage_2fline_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct Line_ExtraEntry_DoNotUseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr Line_ExtraEntry_DoNotUseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 Line_ExtraEntry_DoNotUse_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(Line_ExtraEntry_DoNotUse::InternalGenerateClassData_(
            _default, &Line_ExtraEntry_DoNotUse_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<Line_ExtraEntry_DoNotUse>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~Line_ExtraEntry_DoNotUseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) Line_ExtraEntry_DoNotUse _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<Line_ExtraEntry_DoNotUse>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(Line_ExtraEntry_DoNotUseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST Line_ExtraEntry_DoNotUseGlobalsTypeInternal Line_ExtraEntry_DoNotUse_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* Line_ExtraEntry_DoNotUse_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return Line_ExtraEntry_DoNotUse_globals_.GetClassData();
#else
  return Line_ExtraEntry_DoNotUse_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class LineBackground::_Internal {
 public:
  using HasBits = decltype(::std::declval<LineBackground>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(LineBackground, _impl_._has_bits_);
};

constexpr LineBackground::ParseTableT_ LineBackground::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(LineBackground, _impl_._has_bits_),
      0, // no _extensions_
      5, 24,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967264,  // skipmap
      offsetof(ParseTableT_, field_entries),
      5,  // num_field_entries
      4,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::lyric::storage::LineBackground>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // repeated .lyric.common.Word words = 4 [json_name = "words"];
      {::_pbi::TcParser::FastMtR1,
       {34, 1, 1,
        PROTOBUF_FIELD_OFFSET(LineBackground, _impl_.words_)}},
      // .lyric.common.LineAnnotation annotation = 5 [json_name = "annotation"];
      {::_pbi::TcParser::FastMtS1,
       {42, 3, 2,
        PROTOBUF_FIELD_OFFSET(LineBackground, _impl_.annotation_)}},
      // .lyric.common.Time time = 2 [json_name = "time"];
      {::_pbi::TcParser::FastMtS1,
       {18, 2, 0,
        PROTOBUF_FIELD_OFFSET(LineBackground, _impl_.time_)}},
      // repeated string agents = 3 [json_name = "agents"];
      {::_pbi::TcParser::FastUR1,
       {26, 0, 0,
        PROTOBUF_FIELD_OFFSET(LineBackground, _impl_.agents_)}},
    }}, {{
      65535, 65535
    }}, {{
      // map<string, string> extra = 1 [json_name = "extra"];
      {PROTOBUF_FIELD_OFFSET(LineBackground, _impl_.extra_), _Internal::kHasBitsOffset + 4, 3, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
      // .lyric.common.Time time = 2 [json_name = "time"];
      {PROTOBUF_FIELD_OFFSET(LineBackground, _impl_.time_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
      // repeated string agents = 3 [json_name = "agents"];
      {PROTOBUF_FIELD_OFFSET(LineBackground, _impl_.agents_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
      // repeated .lyric.common.Word words = 4 [json_name = "words"];
      {PROTOBUF_FIELD_OFFSET(LineBackground, _impl_.words_), _Internal::kHasBitsOffset + 1, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
      // .lyric.common.LineAnnotation annotation = 5 [json_name = "annotation"];
      {PROTOBUF_FIELD_OFFSET(LineBackground, _impl_.annotation_), _Internal::kHasBitsOffset + 3, 2, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::lyric::common::Time>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::lyric::common::Time_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::lyric::common::Word>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::lyric::common::Word_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::lyric::common::LineAnnotation>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::lyric::common::LineAnnotation_globals_},
        #endif
        {::_pbi::TcParser::GetMapAuxInfo(
            1, 0, 9, 9, 0)},
    }},
    {{
      "\34\5\0\6\0\0\0\0"
      "lyric.storage.LineBackground"
      "extra"
      "agents"
    }},
  };
}


inline constexpr LineBackground::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        agents_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::LineBackground,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.agents_)>()
         }
        ,
        words_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::LineBackground,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.words_)>()
         }
        ,
        time_{nullptr},
        annotation_{nullptr},
        extra_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::LineBackground,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.extra_)>()
         }
     {}

template <typename>
constexpr LineBackground::LineBackground(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL LineBackground::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) LineBackground(arena);
}
constexpr auto LineBackground::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(LineBackground), alignof(LineBackground));
}
constexpr auto LineBackground::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &LineBackground::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<LineBackground>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &LineBackground::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<LineBackground>(), &LineBackground::ByteSizeLong,
              &LineBackground::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(LineBackground, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_storage_2fline_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct LineBackgroundGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr LineBackgroundGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 LineBackground_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(LineBackground::InternalGenerateClassData_(
            _default, &LineBackground_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<LineBackground>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~LineBackgroundGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) LineBackground _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<LineBackground>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(LineBackgroundGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST LineBackgroundGlobalsTypeInternal LineBackground_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* LineBackground_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return LineBackground_globals_.GetClassData();
#else
  return LineBackground_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class Line::_Internal {
 public:
  using HasBits = decltype(::std::declval<Line>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Line, _impl_._has_bits_);
};

constexpr Line::ParseTableT_ Line::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(Line, _impl_._has_bits_),
      0, // no _extensions_
      7, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967168,  // skipmap
      offsetof(ParseTableT_, field_entries),
      7,  // num_field_entries
      6,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::lyric::storage::Line>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      {::_pbi::TcParser::MiniParse, {}},
      // .lyric.common.Time time = 2 [json_name = "time"];
      {::_pbi::TcParser::FastMtS1,
       {18, 3, 0,
        PROTOBUF_FIELD_OFFSET(Line, _impl_.time_)}},
      // .lyric.common.Part part = 3 [json_name = "part"];
      {::_pbi::TcParser::FastMtS1,
       {26, 4, 1,
        PROTOBUF_FIELD_OFFSET(Line, _impl_.part_)}},
      // repeated string agents = 4 [json_name = "agents"];
      {::_pbi::TcParser::FastUR1,
       {34, 0, 0,
        PROTOBUF_FIELD_OFFSET(Line, _impl_.agents_)}},
      // repeated .lyric.common.Word words = 5 [json_name = "words"];
      {::_pbi::TcParser::FastMtR1,
       {42, 1, 2,
        PROTOBUF_FIELD_OFFSET(Line, _impl_.words_)}},
      // .lyric.common.LineAnnotation annotation = 6 [json_name = "annotation"];
      {::_pbi::TcParser::FastMtS1,
       {50, 5, 3,
        PROTOBUF_FIELD_OFFSET(Line, _impl_.annotation_)}},
      // repeated .lyric.storage.LineBackground backgrounds = 7 [json_name = "backgrounds"];
      {::_pbi::TcParser::FastMtR1,
       {58, 2, 4,
        PROTOBUF_FIELD_OFFSET(Line, _impl_.backgrounds_)}},
    }}, {{
      65535, 65535
    }}, {{
      // map<string, string> extra = 1 [json_name = "extra"];
      {PROTOBUF_FIELD_OFFSET(Line, _impl_.extra_), _Internal::kHasBitsOffset + 6, 5, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
      // .lyric.common.Time time = 2 [json_name = "time"];
      {PROTOBUF_FIELD_OFFSET(Line, _impl_.time_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
      // .lyric.common.Part part = 3 [json_name = "part"];
      {PROTOBUF_FIELD_OFFSET(Line, _impl_.part_), _Internal::kHasBitsOffset + 4, 1, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
      // repeated string agents = 4 [json_name = "agents"];
      {PROTOBUF_FIELD_OFFSET(Line, _impl_.agents_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcRepeated | ::_fl::kUtf8String | ::_fl::kRepSString)},
      // repeated .lyric.common.Word words = 5 [json_name = "words"];
      {PROTOBUF_FIELD_OFFSET(Line, _impl_.words_), _Internal::kHasBitsOffset + 1, 2, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
      // .lyric.common.LineAnnotation annotation = 6 [json_name = "annotation"];
      {PROTOBUF_FIELD_OFFSET(Line, _impl_.annotation_), _Internal::kHasBitsOffset + 5, 3, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
      // repeated .lyric.storage.LineBackground backgrounds = 7 [json_name = "backgrounds"];
      {PROTOBUF_FIELD_OFFSET(Line, _impl_.backgrounds_), _Internal::kHasBitsOffset + 2, 4, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::lyric::common::Time>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::lyric::common::Time_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::lyric::common::Part>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::lyric::common::Part_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::lyric::common::Word>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::lyric::common::Word_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::lyric::common::LineAnnotation>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::lyric::common::LineAnnotation_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::lyric::storage::LineBackground>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::lyric::storage::LineBackground_globals_},
        #endif
        {::_pbi::TcParser::GetMapAuxInfo(
            1, 0, 9, 9, 0)},
    }},
    {{
      "\22\5\0\0\6\0\0\0"
      "lyric.storage.Line"
      "extra"
      "agents"
    }},
  };
}


inline constexpr Line::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        agents_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Line,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.agents_)>()
         }
        ,
        words_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Line,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.words_)>()
         }
        ,
        backgrounds_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Line,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.backgrounds_)>()
         }
        ,
        time_{nullptr},
        part_{nullptr},
        annotation_{nullptr},
        extra_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Line,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.extra_)>()
         }
     {}

template <typename>
constexpr Line::Line(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL Line::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Line(arena);
}
constexpr auto Line::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Line), alignof(Line));
}
constexpr auto Line::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &Line::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Line>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Line::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Line>(), &Line::ByteSizeLong,
              &Line::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Line, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[3],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_storage_2fline_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct LineGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr LineGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 Line_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(Line::InternalGenerateClassData_(
            _default, &Line_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<Line>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~LineGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) Line _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<Line>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(LineGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST LineGlobalsTypeInternal Line_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* Line_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return Line_globals_.GetClassData();
#else
  return Line_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace storage
}  // namespace lyric
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_storage_2fline_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_storage_2fline_2eproto = nullptr;
const ::uint32_t
    TableStruct_storage_2fline_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground_ExtraEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground_ExtraEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground_ExtraEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_._has_bits_),
        8, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.extra_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.time_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.agents_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.words_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.annotation_),
        4,
        2,
        0,
        1,
        3,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Line_ExtraEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Line_ExtraEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Line_ExtraEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_._has_bits_),
        10, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.extra_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.time_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.part_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.agents_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.words_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.annotation_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.backgrounds_),
        6,
        3,
        4,
        0,
        1,
        5,
        2,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::lyric::storage::LineBackground_ExtraEntry_DoNotUse)},
        {7, sizeof(::lyric::storage::LineBackground)},
        {20, sizeof(::lyric::storage::Line_ExtraEntry_DoNotUse)},
        {27, sizeof(::lyric::storage::Line)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::lyric::storage::LineBackground_ExtraEntry_DoNotUse_globals_,
        &::lyric::storage::LineBackground_globals_,
        &::lyric::storage::Line_ExtraEntry_DoNotUse_globals_,
        &::lyric::storage::Line_globals_,
};
const char descriptor_table_protodef_storage_2fline_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\022storage/line.proto\022\rlyric.storage\032\021com"
    "mon/line.proto\032\021common/part.proto\032\021commo"
    "n/time.proto\032\021common/word.proto\"\262\002\n\016Line"
    "Background\022>\n\005extra\030\001 \003(\0132(.lyric.storag"
    "e.LineBackground.ExtraEntryR\005extra\022&\n\004ti"
    "me\030\002 \001(\0132\022.lyric.common.TimeR\004time\022\026\n\006ag"
    "ents\030\003 \003(\tR\006agents\022(\n\005words\030\004 \003(\0132\022.lyri"
    "c.common.WordR\005words\022<\n\nannotation\030\005 \001(\013"
    "2\034.lyric.common.LineAnnotationR\nannotati"
    "on\0328\n\nExtraEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005va"
    "lue\030\002 \001(\tR\005value:\0028\001\"\207\003\n\004Line\0224\n\005extra\030\001"
    " \003(\0132\036.lyric.storage.Line.ExtraEntryR\005ex"
    "tra\022&\n\004time\030\002 \001(\0132\022.lyric.common.TimeR\004t"
    "ime\022&\n\004part\030\003 \001(\0132\022.lyric.common.PartR\004p"
    "art\022\026\n\006agents\030\004 \003(\tR\006agents\022(\n\005words\030\005 \003"
    "(\0132\022.lyric.common.WordR\005words\022<\n\nannotat"
    "ion\030\006 \001(\0132\034.lyric.common.LineAnnotationR"
    "\nannotation\022\?\n\013backgrounds\030\007 \003(\0132\035.lyric"
    ".storage.LineBackgroundR\013backgrounds\0328\n\n"
    "ExtraEntry\022\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 "
    "\001(\tR\005value:\0028\001b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_storage_2fline_2eproto_deps[4] = {
        &::descriptor_table_common_2fline_2eproto,
        &::descriptor_table_common_2fpart_2eproto,
        &::descriptor_table_common_2ftime_2eproto,
        &::descriptor_table_common_2fword_2eproto,
};
static ::absl::once_flag descriptor_table_storage_2fline_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_storage_2fline_2eproto = {
    false,
    false,
    822,
    descriptor_table_protodef_storage_2fline_2eproto,
    "storage/line.proto",
    &descriptor_table_storage_2fline_2eproto_once,
    descriptor_table_storage_2fline_2eproto_deps,
    4,
    4,
    schemas,
    file_message_globals,
    TableStruct_storage_2fline_2eproto::offsets,
    file_level_enum_descriptors_storage_2fline_2eproto,
    file_level_service_descriptors_storage_2fline_2eproto,
};
namespace lyric {
namespace storage {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
LineBackground_ExtraEntry_DoNotUse::LineBackground_ExtraEntry_DoNotUse() : SuperType(LineBackground_ExtraEntry_DoNotUse_get_class_data()) {}
LineBackground_ExtraEntry_DoNotUse::LineBackground_ExtraEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, LineBackground_ExtraEntry_DoNotUse_get_class_data()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
LineBackground_ExtraEntry_DoNotUse::LineBackground_ExtraEntry_DoNotUse() : SuperType() {}
LineBackground_ExtraEntry_DoNotUse::LineBackground_ExtraEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull LineBackground_ExtraEntry_DoNotUse_class_data_ =
        LineBackground_ExtraEntry_DoNotUse::InternalGenerateClassData_(LineBackground_ExtraEntry_DoNotUse_globals_._default);

// including ~ all the vtables and everything they use become part
// of the same ~ SCC.
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
LineBackground_ExtraEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LineBackground_ExtraEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(LineBackground_ExtraEntry_DoNotUse_class_data_.tc_table);
  return LineBackground_ExtraEntry_DoNotUse_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
LineBackground_ExtraEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LineBackground_ExtraEntry_DoNotUse_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&LineBackground_ExtraEntry_DoNotUse_globals_));
  return LineBackground_ExtraEntry_DoNotUse_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const LineBackground_ExtraEntry_DoNotUse::ParseTableT_
    LineBackground_ExtraEntry_DoNotUse::_table_ =
        LineBackground_ExtraEntry_DoNotUse::InternalGenerateParseTable_(LineBackground_ExtraEntry_DoNotUse_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
// ===================================================================

void LineBackground::clear_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.time_ != nullptr) _impl_.time_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000004U);
}
void LineBackground::clear_words() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.words_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
void LineBackground::clear_annotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.annotation_ != nullptr) _impl_.annotation_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
LineBackground::LineBackground(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LineBackground_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lyric.storage.LineBackground)
}
PROTOBUF_NDEBUG_INLINE LineBackground::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::lyric::storage::LineBackground& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        agents_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::lyric::storage::LineBackground,
              PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.agents_)>()
          , from.agents_
        }
        ,
        words_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::lyric::storage::LineBackground,
              PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.words_)>()
          , from.words_
        }
        ,
        extra_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::lyric::storage::LineBackground,
              PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.extra_)>()
          , from.extra_
        }
     {}

LineBackground::LineBackground(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const LineBackground& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, LineBackground_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  LineBackground* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.time_ = (CheckHasBit(cached_has_bits, 0x00000004U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.time_)
                : nullptr;
  _impl_.annotation_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.annotation_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:lyric.storage.LineBackground)
}
PROTOBUF_NDEBUG_INLINE LineBackground::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        agents_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::LineBackground,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.agents_)>()
         }
        ,
        words_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::LineBackground,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.words_)>()
         }
        ,
        extra_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::LineBackground,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::LineBackground, _impl_.extra_)>()
         }
     {}

inline void LineBackground::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, time_),
           0,
           offsetof(Impl_, annotation_) -
               offsetof(Impl_, time_) +
               sizeof(Impl_::annotation_));
}
LineBackground::~LineBackground() {
  // @@protoc_insertion_point(destructor:lyric.storage.LineBackground)
  SharedDtor(*this);
}
inline void LineBackground::SharedDtor(MessageLite& self) {
  LineBackground& this_ = static_cast<LineBackground&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.time_;
  delete this_._impl_.annotation_;
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull LineBackground_class_data_ =
        LineBackground::InternalGenerateClassData_(LineBackground_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
LineBackground::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LineBackground_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(LineBackground_class_data_.tc_table);
  return LineBackground_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
LineBackground::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&LineBackground_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&LineBackground_globals_));
  return LineBackground_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const LineBackground::ParseTableT_
    LineBackground::_table_ =
        LineBackground::InternalGenerateParseTable_(LineBackground_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void LineBackground::Clear() {
// @@protoc_insertion_point(message_clear_start:lyric.storage.LineBackground)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.agents_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.words_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(_impl_.time_ != nullptr);
      _impl_.time_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.annotation_ != nullptr);
      _impl_.annotation_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _impl_.extra_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL LineBackground::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const LineBackground& this_ = static_cast<const LineBackground&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL LineBackground::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const LineBackground& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:lyric.storage.LineBackground)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // map<string, string> extra = 1 [json_name = "extra"];
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (!this_._internal_extra().empty()) {
      using MapType = ::google::protobuf::Map<::std::string, ::std::string>;
      using WireHelper = _pbi::MapEntryFuncs<::std::string, ::std::string,
                                     _pbi::WireFormatLite::TYPE_STRING,
                                     _pbi::WireFormatLite::TYPE_STRING>;
      const auto& field = this_._internal_extra();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              1, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.LineBackground.extra");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.LineBackground.extra");
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              1, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.LineBackground.extra");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.LineBackground.extra");
        }
      }
    }
  }

  // .lyric.common.Time time = 2 [json_name = "time"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.time_, this_._impl_.time_->GetCachedSize(), target,
        stream);
  }

  // repeated string agents = 3 [json_name = "agents"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_agents_size(); i < n; ++i) {
      const auto& s = this_._internal_agents().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.LineBackground.agents");
      target = stream->WriteString(3, s, target);
    }
  }

  // repeated .lyric.common.Word words = 4 [json_name = "words"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_words_size());
         i < n; i++) {
      const auto& repfield = this_._internal_words().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              4, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // .lyric.common.LineAnnotation annotation = 5 [json_name = "annotation"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        5, *this_._impl_.annotation_, this_._impl_.annotation_->GetCachedSize(), target,
        stream);
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lyric.storage.LineBackground)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t LineBackground::ByteSizeLong(const MessageLite& base) {
  const LineBackground& this_ = static_cast<const LineBackground&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t LineBackground::ByteSizeLong() const {
  const LineBackground& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:lyric.storage.LineBackground)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    // repeated string agents = 3 [json_name = "agents"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_agents().size());
      for (int i = 0, n = this_._internal_agents().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_agents().Get(i));
      }
    }
    // repeated .lyric.common.Word words = 4 [json_name = "words"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_words_size();
      for (const auto& msg : this_._internal_words()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // .lyric.common.Time time = 2 [json_name = "time"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.time_);
    }
    // .lyric.common.LineAnnotation annotation = 5 [json_name = "annotation"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.annotation_);
    }
    // map<string, string> extra = 1 [json_name = "extra"];
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_extra_size());
      for (const auto& entry : this_._internal_extra()) {
        total_size += _pbi::MapEntryFuncs<::std::string, ::std::string,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void LineBackground::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<LineBackground*>(&to_msg);
  auto& from = static_cast<const LineBackground&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lyric.storage.LineBackground)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000001fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_agents()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_agents());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_words()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_words());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      ABSL_DCHECK(from._impl_.time_ != nullptr);
      if (_this->_impl_.time_ == nullptr) {
        _this->_impl_.time_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.time_);
      } else {
        _this->_impl_.time_->MergeFrom(*from._impl_.time_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.annotation_ != nullptr);
      if (_this->_impl_.annotation_ == nullptr) {
        _this->_impl_.annotation_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.annotation_);
      } else {
        _this->_impl_.annotation_->MergeFrom(*from._impl_.annotation_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      _this->_impl_.extra_.MergeFrom(from._impl_.extra_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void LineBackground::CopyFrom(const LineBackground& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:lyric.storage.LineBackground)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void LineBackground::InternalSwap(LineBackground* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.agents_.InternalSwap(&other->_impl_.agents_);
  _impl_.words_.InternalSwap(&other->_impl_.words_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(LineBackground, _impl_.annotation_)
      + sizeof(LineBackground::_impl_.annotation_)
      - PROTOBUF_FIELD_OFFSET(LineBackground, _impl_.time_)>(
          reinterpret_cast<char*>(&_impl_.time_),
          reinterpret_cast<char*>(&other->_impl_.time_));
  _impl_.extra_.InternalSwap(&other->_impl_.extra_);
}

::google::protobuf::Metadata LineBackground::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
Line_ExtraEntry_DoNotUse::Line_ExtraEntry_DoNotUse() : SuperType(Line_ExtraEntry_DoNotUse_get_class_data()) {}
Line_ExtraEntry_DoNotUse::Line_ExtraEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, Line_ExtraEntry_DoNotUse_get_class_data()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
Line_ExtraEntry_DoNotUse::Line_ExtraEntry_DoNotUse() : SuperType() {}
Line_ExtraEntry_DoNotUse::Line_ExtraEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Line_ExtraEntry_DoNotUse_class_data_ =
        Line_ExtraEntry_DoNotUse::InternalGenerateClassData_(Line_ExtraEntry_DoNotUse_globals_._default);

// including ~ all the vtables and everything they use become part
// of the same ~ SCC.
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Line_ExtraEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Line_ExtraEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Line_ExtraEntry_DoNotUse_class_data_.tc_table);
  return Line_ExtraEntry_DoNotUse_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Line_ExtraEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Line_ExtraEntry_DoNotUse_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&Line_ExtraEntry_DoNotUse_globals_));
  return Line_ExtraEntry_DoNotUse_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const Line_ExtraEntry_DoNotUse::ParseTableT_
    Line_ExtraEntry_DoNotUse::_table_ =
        Line_ExtraEntry_DoNotUse::InternalGenerateParseTable_(Line_ExtraEntry_DoNotUse_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
// ===================================================================

void Line::clear_time() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.time_ != nullptr) _impl_.time_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
void Line::clear_part() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.part_ != nullptr) _impl_.part_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000010U);
}
void Line::clear_words() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.words_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
void Line::clear_annotation() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.annotation_ != nullptr) _impl_.annotation_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000020U);
}
Line::Line(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Line_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lyric.storage.Line)
}
PROTOBUF_NDEBUG_INLINE Line::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::lyric::storage::Line& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        agents_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::lyric::storage::Line,
              PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.agents_)>()
          , from.agents_
        }
        ,
        words_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::lyric::storage::Line,
              PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.words_)>()
          , from.words_
        }
        ,
        backgrounds_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::lyric::storage::Line,
              PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.backgrounds_)>()
          , from.backgrounds_
        }
        ,
        extra_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::lyric::storage::Line,
              PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.extra_)>()
          , from.extra_
        }
     {}

Line::Line(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Line& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Line_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Line* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.time_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.time_)
                : nullptr;
  _impl_.part_ = (CheckHasBit(cached_has_bits, 0x00000010U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.part_)
                : nullptr;
  _impl_.annotation_ = (CheckHasBit(cached_has_bits, 0x00000020U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.annotation_)
                : nullptr;

  // @@protoc_insertion_point(copy_constructor:lyric.storage.Line)
}
PROTOBUF_NDEBUG_INLINE Line::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        agents_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Line,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.agents_)>()
         }
        ,
        words_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Line,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.words_)>()
         }
        ,
        backgrounds_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Line,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.backgrounds_)>()
         }
        ,
        extra_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Line,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Line, _impl_.extra_)>()
         }
     {}

inline void Line::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, time_),
           0,
           offsetof(Impl_, annotation_) -
               offsetof(Impl_, time_) +
               sizeof(Impl_::annotation_));
}
Line::~Line() {
  // @@protoc_insertion_point(destructor:lyric.storage.Line)
  SharedDtor(*this);
}
inline void Line::SharedDtor(MessageLite& self) {
  Line& this_ = static_cast<Line&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  delete this_._impl_.time_;
  delete this_._impl_.part_;
  delete this_._impl_.annotation_;
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Line_class_data_ =
        Line::InternalGenerateClassData_(Line_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Line::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Line_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Line_class_data_.tc_table);
  return Line_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Line::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Line_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&Line_globals_));
  return Line_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const Line::ParseTableT_
    Line::_table_ =
        Line::InternalGenerateParseTable_(Line_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void Line::Clear() {
// @@protoc_insertion_point(message_clear_start:lyric.storage.Line)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.agents_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.words_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.backgrounds_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.time_ != nullptr);
      _impl_.time_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(_impl_.part_ != nullptr);
      _impl_.part_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(_impl_.annotation_ != nullptr);
      _impl_.annotation_->Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _impl_.extra_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Line::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Line& this_ = static_cast<const Line&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Line::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Line& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:lyric.storage.Line)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // map<string, string> extra = 1 [json_name = "extra"];
  if (CheckHasBit(cached_has_bits, 0x00000040U)) {
    if (!this_._internal_extra().empty()) {
      using MapType = ::google::protobuf::Map<::std::string, ::std::string>;
      using WireHelper = _pbi::MapEntryFuncs<::std::string, ::std::string,
                                     _pbi::WireFormatLite::TYPE_STRING,
                                     _pbi::WireFormatLite::TYPE_STRING>;
      const auto& field = this_._internal_extra();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              1, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.Line.extra");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.Line.extra");
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              1, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.Line.extra");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.Line.extra");
        }
      }
    }
  }

  // .lyric.common.Time time = 2 [json_name = "time"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        2, *this_._impl_.time_, this_._impl_.time_->GetCachedSize(), target,
        stream);
  }

  // .lyric.common.Part part = 3 [json_name = "part"];
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        3, *this_._impl_.part_, this_._impl_.part_->GetCachedSize(), target,
        stream);
  }

  // repeated string agents = 4 [json_name = "agents"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (int i = 0, n = this_._internal_agents_size(); i < n; ++i) {
      const auto& s = this_._internal_agents().Get(i);
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          s.data(), static_cast<int>(s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.Line.agents");
      target = stream->WriteString(4, s, target);
    }
  }

  // repeated .lyric.common.Word words = 5 [json_name = "words"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_words_size());
         i < n; i++) {
      const auto& repfield = this_._internal_words().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              5, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // .lyric.common.LineAnnotation annotation = 6 [json_name = "annotation"];
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        6, *this_._impl_.annotation_, this_._impl_.annotation_->GetCachedSize(), target,
        stream);
  }

  // repeated .lyric.storage.LineBackground backgrounds = 7 [json_name = "backgrounds"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_backgrounds_size());
         i < n; i++) {
      const auto& repfield = this_._internal_backgrounds().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              7, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lyric.storage.Line)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Line::ByteSizeLong(const MessageLite& base) {
  const Line& this_ = static_cast<const Line&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Line::ByteSizeLong() const {
  const Line& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:lyric.storage.Line)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    // repeated string agents = 4 [json_name = "agents"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_agents().size());
      for (int i = 0, n = this_._internal_agents().size(); i < n; ++i) {
        total_size += ::google::protobuf::internal::WireFormatLite::StringSize(
            this_._internal_agents().Get(i));
      }
    }
    // repeated .lyric.common.Word words = 5 [json_name = "words"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_words_size();
      for (const auto& msg : this_._internal_words()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .lyric.storage.LineBackground backgrounds = 7 [json_name = "backgrounds"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      total_size += 1UL * this_._internal_backgrounds_size();
      for (const auto& msg : this_._internal_backgrounds()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // .lyric.common.Time time = 2 [json_name = "time"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.time_);
    }
    // .lyric.common.Part part = 3 [json_name = "part"];
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.part_);
    }
    // .lyric.common.LineAnnotation annotation = 6 [json_name = "annotation"];
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.annotation_);
    }
    // map<string, string> extra = 1 [json_name = "extra"];
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_extra_size());
      for (const auto& entry : this_._internal_extra()) {
        total_size += _pbi::MapEntryFuncs<::std::string, ::std::string,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Line::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<Line*>(&to_msg);
  auto& from = static_cast<const Line&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lyric.storage.Line)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000007fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_agents()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_agents());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_words()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_words());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _this->_internal_mutable_backgrounds()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_backgrounds());
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.time_ != nullptr);
      if (_this->_impl_.time_ == nullptr) {
        _this->_impl_.time_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.time_);
      } else {
        _this->_impl_.time_->MergeFrom(*from._impl_.time_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      ABSL_DCHECK(from._impl_.part_ != nullptr);
      if (_this->_impl_.part_ == nullptr) {
        _this->_impl_.part_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.part_);
      } else {
        _this->_impl_.part_->MergeFrom(*from._impl_.part_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      ABSL_DCHECK(from._impl_.annotation_ != nullptr);
      if (_this->_impl_.annotation_ == nullptr) {
        _this->_impl_.annotation_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.annotation_);
      } else {
        _this->_impl_.annotation_->MergeFrom(*from._impl_.annotation_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000040U)) {
      _this->_impl_.extra_.MergeFrom(from._impl_.extra_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Line::CopyFrom(const Line& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:lyric.storage.Line)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Line::InternalSwap(Line* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.agents_.InternalSwap(&other->_impl_.agents_);
  _impl_.words_.InternalSwap(&other->_impl_.words_);
  _impl_.backgrounds_.InternalSwap(&other->_impl_.backgrounds_);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Line, _impl_.annotation_)
      + sizeof(Line::_impl_.annotation_)
      - PROTOBUF_FIELD_OFFSET(Line, _impl_.time_)>(
          reinterpret_cast<char*>(&_impl_.time_),
          reinterpret_cast<char*>(&other->_impl_.time_));
  _impl_.extra_.InternalSwap(&other->_impl_.extra_);
}

::google::protobuf::Metadata Line::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace storage
}  // namespace lyric
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_storage_2fline_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
