// Generated by the protocol buffer compiler.  DO NOT EDIT!
// NO CHECKED-IN PROTOBUF GENCODE
// source: storage/lyric.proto
// Protobuf C++ Version: 7.35.1

#include "storage/lyric.pb.h"

#include <algorithm>
#include <type_traits>
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/generated_message_tctable_impl.h"
#include "google/protobuf/internal_visibility.h"
#include "google/protobuf/extension_set.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/wire_format_lite.h"
#include "google/protobuf/descriptor.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/reflection_ops.h"
#include "google/protobuf/wire_format.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"
PROTOBUF_PRAGMA_INIT_SEG
namespace _pb = ::google::protobuf;
namespace _pbi = ::google::protobuf::internal;
namespace _fl = ::google::protobuf::internal::field_layout;
#ifdef PROTOBUF_MESSAGE_GLOBALS
namespace {
PROTOBUF_CONSTINIT ::google::protobuf::internal::ReflectionData
    file_reflection_data[] = {
        // ::lyric::storage::Lyric_ExtraEntry_DoNotUse
        {&::_pbi::kDescriptorMethods, &::descriptor_table_storage_2flyric_2eproto, /* tracker*/ nullptr,},
        // ::lyric::storage::Lyric
        {&::_pbi::kDescriptorMethods, &::descriptor_table_storage_2flyric_2eproto, /* tracker*/ nullptr,},
};
}  // namespace
#endif
namespace lyric {
namespace storage {
constexpr Lyric_ExtraEntry_DoNotUse::ParseTableT_ Lyric_ExtraEntry_DoNotUse::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(Lyric_ExtraEntry_DoNotUse, _impl_._has_bits_),
      0, // no _extensions_
      2, 8,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967292,  // skipmap
      offsetof(ParseTableT_, field_entries),
      2,  // num_field_entries
      0,  // num_aux_entries
      offsetof(ParseTableT_, field_names),  // no aux_entries
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::DiscardEverythingFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::lyric::storage::Lyric_ExtraEntry_DoNotUse>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      // string value = 2 [json_name = "value"];
      {::_pbi::TcParser::FastUS1,
       {18, 1, 0,
        PROTOBUF_FIELD_OFFSET(Lyric_ExtraEntry_DoNotUse, _impl_.value_)}},
      // string key = 1 [json_name = "key"];
      {::_pbi::TcParser::FastUS1,
       {10, 0, 0,
        PROTOBUF_FIELD_OFFSET(Lyric_ExtraEntry_DoNotUse, _impl_.key_)}},
    }}, {{
      65535, 65535
    }}, {{
      // string key = 1 [json_name = "key"];
      {PROTOBUF_FIELD_OFFSET(Lyric_ExtraEntry_DoNotUse, _impl_.key_), _Internal::kHasBitsOffset + 0, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // string value = 2 [json_name = "value"];
      {PROTOBUF_FIELD_OFFSET(Lyric_ExtraEntry_DoNotUse, _impl_.value_), _Internal::kHasBitsOffset + 1, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
    }},
    // no aux_entries
    {{
      "\36\3\5\0\0\0\0\0"
      "lyric.storage.Lyric.ExtraEntry"
      "key"
      "value"
    }},
  };
}

template <typename>
constexpr Lyric_ExtraEntry_DoNotUse::Lyric_ExtraEntry_DoNotUse(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : Lyric_ExtraEntry_DoNotUse::MapEntry(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
      ) {
}
inline void* PROTOBUF_NONNULL Lyric_ExtraEntry_DoNotUse::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Lyric_ExtraEntry_DoNotUse(arena);
}
constexpr auto Lyric_ExtraEntry_DoNotUse::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Lyric_ExtraEntry_DoNotUse), alignof(Lyric_ExtraEntry_DoNotUse));
}
constexpr auto Lyric_ExtraEntry_DoNotUse::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &Lyric_ExtraEntry_DoNotUse::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Lyric_ExtraEntry_DoNotUse>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Lyric_ExtraEntry_DoNotUse::SharedDtor,
          static_cast<void (::google::protobuf::MessageLite::*)()>(&Lyric_ExtraEntry_DoNotUse::ClearImpl),
              ::google::protobuf::Message::ByteSizeLongImpl, ::google::protobuf::Message::_InternalSerializeImpl
              ,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Lyric_ExtraEntry_DoNotUse, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[0],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_storage_2flyric_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct Lyric_ExtraEntry_DoNotUseGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr Lyric_ExtraEntry_DoNotUseGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 Lyric_ExtraEntry_DoNotUse_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(Lyric_ExtraEntry_DoNotUse::InternalGenerateClassData_(
            _default, &Lyric_ExtraEntry_DoNotUse_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<Lyric_ExtraEntry_DoNotUse>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~Lyric_ExtraEntry_DoNotUseGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) Lyric_ExtraEntry_DoNotUse _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<Lyric_ExtraEntry_DoNotUse>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(Lyric_ExtraEntry_DoNotUseGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST Lyric_ExtraEntry_DoNotUseGlobalsTypeInternal Lyric_ExtraEntry_DoNotUse_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* Lyric_ExtraEntry_DoNotUse_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return Lyric_ExtraEntry_DoNotUse_globals_.GetClassData();
#else
  return Lyric_ExtraEntry_DoNotUse_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
class Lyric::_Internal {
 public:
  using HasBits = decltype(::std::declval<Lyric>()._impl_._has_bits_);
  static constexpr ::int32_t kHasBitsOffset =
      8 * PROTOBUF_FIELD_OFFSET(Lyric, _impl_._has_bits_);
};

constexpr Lyric::ParseTableT_ Lyric::InternalGenerateParseTable_(const ::_pbi::ClassData* class_data) {
  return ParseTableT_{
    {
      PROTOBUF_FIELD_OFFSET(Lyric, _impl_._has_bits_),
      0, // no _extensions_
      6, 56,  // max_field_number, fast_idx_mask
      offsetof(ParseTableT_, field_lookup_table),
      4294967232,  // skipmap
      offsetof(ParseTableT_, field_entries),
      6,  // num_field_entries
      4,  // num_aux_entries
      offsetof(ParseTableT_, aux_entries),
      class_data,
      nullptr,  // post_loop_handler
      ::_pbi::TcParser::GenericFallback,  // fallback
      #ifdef PROTOBUF_PREFETCH_PARSE_TABLE
      ::_pbi::TcParser::GetTable<::lyric::storage::Lyric>(),  // to_prefetch
      #endif  // PROTOBUF_PREFETCH_PARSE_TABLE
    }, {{
      {::_pbi::TcParser::MiniParse, {}},
      // string version = 1 [json_name = "version"];
      {::_pbi::TcParser::FastUS1,
       {10, 2, 0,
        PROTOBUF_FIELD_OFFSET(Lyric, _impl_.version_)}},
      // .lyric.common.Timing timing = 2 [json_name = "timing"];
      {::_pbi::TcParser::SingularVarintNoZag1<::uint32_t, offsetof(Lyric, _impl_.timing_), 4>(),
       {16, 4, 0,
        PROTOBUF_FIELD_OFFSET(Lyric, _impl_.timing_)}},
      {::_pbi::TcParser::MiniParse, {}},
      // .lyric.common.Meta meta = 4 [json_name = "meta"];
      {::_pbi::TcParser::FastMtS1,
       {34, 3, 0,
        PROTOBUF_FIELD_OFFSET(Lyric, _impl_.meta_)}},
      // repeated .lyric.common.AgentItem agents = 5 [json_name = "agents"];
      {::_pbi::TcParser::FastMtR1,
       {42, 0, 1,
        PROTOBUF_FIELD_OFFSET(Lyric, _impl_.agents_)}},
      // repeated .lyric.storage.Line lines = 6 [json_name = "lines"];
      {::_pbi::TcParser::FastMtR1,
       {50, 1, 2,
        PROTOBUF_FIELD_OFFSET(Lyric, _impl_.lines_)}},
      {::_pbi::TcParser::MiniParse, {}},
    }}, {{
      65535, 65535
    }}, {{
      // string version = 1 [json_name = "version"];
      {PROTOBUF_FIELD_OFFSET(Lyric, _impl_.version_), _Internal::kHasBitsOffset + 2, 0, (0 | ::_fl::kFcOptional | ::_fl::kUtf8String | ::_fl::kRepAString)},
      // .lyric.common.Timing timing = 2 [json_name = "timing"];
      {PROTOBUF_FIELD_OFFSET(Lyric, _impl_.timing_), _Internal::kHasBitsOffset + 4, 0, (0 | ::_fl::kFcOptional | ::_fl::kOpenEnum)},
      // map<string, string> extra = 3 [json_name = "extra"];
      {PROTOBUF_FIELD_OFFSET(Lyric, _impl_.extra_), _Internal::kHasBitsOffset + 5, 3, (0 | ::_fl::kFcRepeated | ::_fl::kMap)},
      // .lyric.common.Meta meta = 4 [json_name = "meta"];
      {PROTOBUF_FIELD_OFFSET(Lyric, _impl_.meta_), _Internal::kHasBitsOffset + 3, 0, (0 | ::_fl::kFcOptional | ::_fl::kMessage | ::_fl::kTvTable)},
      // repeated .lyric.common.AgentItem agents = 5 [json_name = "agents"];
      {PROTOBUF_FIELD_OFFSET(Lyric, _impl_.agents_), _Internal::kHasBitsOffset + 0, 1, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
      // repeated .lyric.storage.Line lines = 6 [json_name = "lines"];
      {PROTOBUF_FIELD_OFFSET(Lyric, _impl_.lines_), _Internal::kHasBitsOffset + 1, 2, (0 | ::_fl::kFcRepeated | ::_fl::kMessage | ::_fl::kTvTable)},
    }},
    {{
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::lyric::common::Meta>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::lyric::common::Meta_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::lyric::common::AgentItem>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::lyric::common::AgentItem_globals_},
        #endif
        #ifndef PROTOBUF_MESSAGE_GLOBALS
        {::_pbi::TcParser::GetTable<::lyric::storage::Line>()},
        #else
        {::_pbi::FieldAuxMessageGlobals(), &::lyric::storage::Line_globals_},
        #endif
        {::_pbi::TcParser::GetMapAuxInfo(
            1, 0, 9, 9, 0)},
    }},
    {{
      "\23\7\0\5\0\0\0\0"
      "lyric.storage.Lyric"
      "version"
      "extra"
    }},
  };
}


inline constexpr Lyric::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    ::_pbi::ConstantInitialized) noexcept
      : _cached_size_{0},
        agents_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Lyric,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.agents_)>()
         }
        ,
        lines_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Lyric,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.lines_)>()
         }
        ,
        version_(
            &::google::protobuf::internal::fixed_address_empty_string,
            ::_pbi::ConstantInitialized()),
        meta_{nullptr},
        timing_{static_cast< ::lyric::common::Timing >(0)},
        extra_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Lyric,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.extra_)>()
         }
     {}

template <typename>
constexpr Lyric::Lyric(::_pbi::ConstantInitialized,
                       const ::_pbi::ClassData* PROTOBUF_NONNULL class_data)
    : ::google::protobuf::Message(
#if defined(PROTOBUF_CUSTOM_VTABLE)
          class_data
#endif  // PROTOBUF_CUSTOM_VTABLE
          ),
      _impl_(internal_visibility(), ::_pbi::ConstantInitialized()) {
}
inline void* PROTOBUF_NONNULL Lyric::PlacementNew_(
    const void* PROTOBUF_NONNULL, void* PROTOBUF_NONNULL mem,
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena) {
  return ::new (mem) Lyric(arena);
}
constexpr auto Lyric::InternalNewImpl_() {
  return ::google::protobuf::internal::MessageCreator::CopyInit(sizeof(Lyric), alignof(Lyric));
}
constexpr auto Lyric::InternalGenerateClassData_(
    const MessageLite& prototype,
    const ::google::protobuf::internal::TcParseTableBase* tc_table) {
  return ::google::protobuf::internal::ClassDataFull{
      ::google::protobuf::internal::ClassData{
          &prototype,
#ifndef PROTOBUF_MESSAGE_GLOBALS
          &_table_.header,
#else
          tc_table,
#endif
          nullptr,  // IsInitialized
          &Lyric::MergeImpl,
          ::google::protobuf::Message::GetNewImpl<Lyric>(),
#if defined(PROTOBUF_CUSTOM_VTABLE)
          &Lyric::SharedDtor,
          ::google::protobuf::Message::GetClearImpl<Lyric>(), &Lyric::ByteSizeLong,
              &Lyric::_InternalSerialize,
#endif  // PROTOBUF_CUSTOM_VTABLE
          PROTOBUF_FIELD_OFFSET(Lyric, _impl_._cached_size_),
          false,
      },
#ifdef PROTOBUF_MESSAGE_GLOBALS
      &file_reflection_data[1],
#else   // !PROTOBUF_MESSAGE_GLOBALS
      &::_pbi::kDescriptorMethods,
      &descriptor_table_storage_2flyric_2eproto,
      nullptr,  // tracker
#endif  // PROTOBUF_MESSAGE_GLOBALS
  };
}
struct LyricGlobalsTypeInternal : ::_pbi::MessageGlobalsBase {
  constexpr LyricGlobalsTypeInternal()
      :
#ifndef PROTOBUF_MESSAGE_GLOBALS
        _default(::_pbi::ConstantInitialized{},
                 Lyric_class_data_.base())
#else   // !PROTOBUF_MESSAGE_GLOBALS
        MessageGlobalsBase(Lyric::InternalGenerateClassData_(
            _default, &Lyric_globals_._table.header)),
        _default(::_pbi::ConstantInitialized{}, GetClassData()),
        _table(::_pbi::PrivateAccess::GenerateParseTable<Lyric>(
            GetClassData()))
#endif  // PROTOBUF_MESSAGE_GLOBALS
  {
  }
  ~LyricGlobalsTypeInternal() {}
  union {
    alignas(::_pbi::kMaxMessageAlignment) Lyric _default;
  };
#ifdef PROTOBUF_MESSAGE_GLOBALS
  decltype(::_pbi::PrivateAccess::GenerateParseTable<Lyric>(
      ::std::declval<const ::_pbi::ClassData*>())) _table;
#endif
};
#ifdef PROTOBUF_MESSAGE_GLOBALS
static_assert(PROTOBUF_FIELD_OFFSET(LyricGlobalsTypeInternal, _default) ==
              ::_pbi::MessageGlobalsBase::OffsetToDefault());
#endif  // PROTOBUF_MESSAGE_GLOBALS

PROTOBUF_ATTRIBUTE_NO_DESTROY PROTOBUF_CONSTINIT
    PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 PROTOBUF_MESSAGE_GLOBALS_CONST LyricGlobalsTypeInternal Lyric_globals_
        PROTOBUF_MESSAGE_GLOBALS_SECTION(.data.rel.ro);
#if defined(PROTOBUF_CUSTOM_VTABLE)
namespace {
const ::_pbi::ClassData* Lyric_get_class_data() {
#ifdef PROTOBUF_MESSAGE_GLOBALS
  return Lyric_globals_.GetClassData();
#else
  return Lyric_class_data_.base();
#endif  // PROTOBUF_MESSAGE_GLOBALS
}
}  // namespace
#endif  // PROTOBUF_CUSTOM_VTABLE
}  // namespace storage
}  // namespace lyric
static constexpr const ::_pb::EnumDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_enum_descriptors_storage_2flyric_2eproto = nullptr;
static constexpr const ::_pb::ServiceDescriptor* PROTOBUF_NONNULL* PROTOBUF_NULLABLE
    file_level_service_descriptors_storage_2flyric_2eproto = nullptr;
const ::uint32_t
    TableStruct_storage_2flyric_2eproto::offsets[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
        protodesc_cold) = {
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric_ExtraEntry_DoNotUse, _impl_._has_bits_),
        5, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric_ExtraEntry_DoNotUse, _impl_.key_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric_ExtraEntry_DoNotUse, _impl_.value_),
        0,
        1,
        0x081, // bitmap
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_._has_bits_),
        9, // hasbit index offset
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.version_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.timing_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.extra_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.meta_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.agents_),
        PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.lines_),
        2,
        4,
        5,
        3,
        0,
        1,
};

static const ::_pbi::MigrationSchema
    schemas[] ABSL_ATTRIBUTE_SECTION_VARIABLE(protodesc_cold) = {
        {0, sizeof(::lyric::storage::Lyric_ExtraEntry_DoNotUse)},
        {7, sizeof(::lyric::storage::Lyric)},
};
static const ::_pbi::MessageGlobalsBase* PROTOBUF_NONNULL const
    file_message_globals[] = {
        &::lyric::storage::Lyric_ExtraEntry_DoNotUse_globals_,
        &::lyric::storage::Lyric_globals_,
};
const char descriptor_table_protodef_storage_2flyric_2eproto[] ABSL_ATTRIBUTE_SECTION_VARIABLE(
    protodesc_cold) = {
    "\n\023storage/lyric.proto\022\rlyric.storage\032\022co"
    "mmon/agent.proto\032\021common/meta.proto\032\023com"
    "mon/timing.proto\032\022storage/line.proto\"\304\002\n"
    "\005Lyric\022\030\n\007version\030\001 \001(\tR\007version\022,\n\006timi"
    "ng\030\002 \001(\0162\024.lyric.common.TimingR\006timing\0225"
    "\n\005extra\030\003 \003(\0132\037.lyric.storage.Lyric.Extr"
    "aEntryR\005extra\022&\n\004meta\030\004 \001(\0132\022.lyric.comm"
    "on.MetaR\004meta\022/\n\006agents\030\005 \003(\0132\027.lyric.co"
    "mmon.AgentItemR\006agents\022)\n\005lines\030\006 \003(\0132\023."
    "lyric.storage.LineR\005lines\0328\n\nExtraEntry\022"
    "\020\n\003key\030\001 \001(\tR\003key\022\024\n\005value\030\002 \001(\tR\005value:"
    "\0028\001b\006proto3"
};
static const ::_pbi::DescriptorTable* PROTOBUF_NONNULL const
    descriptor_table_storage_2flyric_2eproto_deps[4] = {
        &::descriptor_table_common_2fagent_2eproto,
        &::descriptor_table_common_2fmeta_2eproto,
        &::descriptor_table_common_2ftiming_2eproto,
        &::descriptor_table_storage_2fline_2eproto,
};
static ::absl::once_flag descriptor_table_storage_2flyric_2eproto_once;
PROTOBUF_CONSTINIT const ::_pbi::DescriptorTable descriptor_table_storage_2flyric_2eproto = {
    false,
    false,
    451,
    descriptor_table_protodef_storage_2flyric_2eproto,
    "storage/lyric.proto",
    &descriptor_table_storage_2flyric_2eproto_once,
    descriptor_table_storage_2flyric_2eproto_deps,
    4,
    2,
    schemas,
    file_message_globals,
    TableStruct_storage_2flyric_2eproto::offsets,
    file_level_enum_descriptors_storage_2flyric_2eproto,
    file_level_service_descriptors_storage_2flyric_2eproto,
};
namespace lyric {
namespace storage {
// ===================================================================

#if defined(PROTOBUF_CUSTOM_VTABLE)
Lyric_ExtraEntry_DoNotUse::Lyric_ExtraEntry_DoNotUse() : SuperType(Lyric_ExtraEntry_DoNotUse_get_class_data()) {}
Lyric_ExtraEntry_DoNotUse::Lyric_ExtraEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
    : SuperType(arena, Lyric_ExtraEntry_DoNotUse_get_class_data()) {}
#else   // PROTOBUF_CUSTOM_VTABLE
Lyric_ExtraEntry_DoNotUse::Lyric_ExtraEntry_DoNotUse() : SuperType() {}
Lyric_ExtraEntry_DoNotUse::Lyric_ExtraEntry_DoNotUse(::google::protobuf::Arena* PROTOBUF_NULLABLE arena) : SuperType(arena) {}
#endif  // PROTOBUF_CUSTOM_VTABLE
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Lyric_ExtraEntry_DoNotUse_class_data_ =
        Lyric_ExtraEntry_DoNotUse::InternalGenerateClassData_(Lyric_ExtraEntry_DoNotUse_globals_._default);

// including ~ all the vtables and everything they use become part
// of the same ~ SCC.
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Lyric_ExtraEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Lyric_ExtraEntry_DoNotUse_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Lyric_ExtraEntry_DoNotUse_class_data_.tc_table);
  return Lyric_ExtraEntry_DoNotUse_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Lyric_ExtraEntry_DoNotUse::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Lyric_ExtraEntry_DoNotUse_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&Lyric_ExtraEntry_DoNotUse_globals_));
  return Lyric_ExtraEntry_DoNotUse_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const Lyric_ExtraEntry_DoNotUse::ParseTableT_
    Lyric_ExtraEntry_DoNotUse::_table_ =
        Lyric_ExtraEntry_DoNotUse::InternalGenerateParseTable_(Lyric_ExtraEntry_DoNotUse_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
// ===================================================================

void Lyric::clear_meta() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  if (_impl_.meta_ != nullptr) _impl_.meta_->Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000008U);
}
void Lyric::clear_agents() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.agents_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000001U);
}
void Lyric::clear_lines() {
  ::google::protobuf::internal::TSanWrite(&_impl_);
  _impl_.lines_.Clear();
  ClearHasBit(_impl_._has_bits_[0], 0x00000002U);
}
Lyric::Lyric(::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Lyric_get_class_data()) {
#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  SharedCtor(arena);
  // @@protoc_insertion_point(arena_constructor:lyric.storage.Lyric)
}
PROTOBUF_NDEBUG_INLINE Lyric::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena, const Impl_& from,
    [[maybe_unused]] const ::lyric::storage::Lyric& from_msg)
      : _has_bits_{from._has_bits_},
        _cached_size_{0},
        agents_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::lyric::storage::Lyric,
              PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.agents_)>()
          , from.agents_
        }
        ,
        lines_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::lyric::storage::Lyric,
              PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.lines_)>()
          , from.lines_
        }
        ,
        version_(arena, from.version_),
        extra_ {
          visibility, ::_pbi::InternalMetadataOffset::Build<
              ::lyric::storage::Lyric,
              PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.extra_)>()
          , from.extra_
        }
     {}

Lyric::Lyric(
    ::google::protobuf::Arena* PROTOBUF_NULLABLE arena,
    const Lyric& from)
#if defined(PROTOBUF_CUSTOM_VTABLE)
    : ::google::protobuf::Message(arena, Lyric_get_class_data()) {

#else   // PROTOBUF_CUSTOM_VTABLE
    : ::google::protobuf::Message(arena) {
#endif  // PROTOBUF_CUSTOM_VTABLE
  Lyric* const _this = this;
  (void)_this;
  _internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
  new (&_impl_) Impl_(internal_visibility(), arena, from._impl_, from);
  ::uint32_t cached_has_bits = _impl_._has_bits_[0];
  _impl_.meta_ = (CheckHasBit(cached_has_bits, 0x00000008U))
                ? ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.meta_)
                : nullptr;
  _impl_.timing_ = from._impl_.timing_;

  // @@protoc_insertion_point(copy_constructor:lyric.storage.Lyric)
}
PROTOBUF_NDEBUG_INLINE Lyric::Impl_::Impl_(
    [[maybe_unused]] ::google::protobuf::internal::InternalVisibility visibility,
    [[maybe_unused]] ::google::protobuf::Arena* PROTOBUF_NULLABLE arena)
      : _cached_size_{0},
        agents_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Lyric,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.agents_)>()
         }
        ,
        lines_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Lyric,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.lines_)>()
         }
        ,
        version_(arena),
        extra_ { visibility, ::_pbi::InternalMetadataOffset::Build<
            ::lyric::storage::Lyric,
            PROTOBUF_FIELD_OFFSET(::lyric::storage::Lyric, _impl_.extra_)>()
         }
     {}

inline void Lyric::SharedCtor(::_pb::Arena* PROTOBUF_NULLABLE arena) {
  new (&_impl_) Impl_(internal_visibility(), arena);
  ::memset(reinterpret_cast<char*>(&_impl_) +
               offsetof(Impl_, meta_),
           0,
           offsetof(Impl_, timing_) -
               offsetof(Impl_, meta_) +
               sizeof(Impl_::timing_));
}
Lyric::~Lyric() {
  // @@protoc_insertion_point(destructor:lyric.storage.Lyric)
  SharedDtor(*this);
}
inline void Lyric::SharedDtor(MessageLite& self) {
  Lyric& this_ = static_cast<Lyric&>(self);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  this_._internal_metadata_.Delete<::google::protobuf::UnknownFieldSet>();
  ABSL_DCHECK(this_.GetArena() == nullptr);
  this_._impl_.version_.Destroy();
  delete this_._impl_.meta_;
  this_._impl_.~Impl_();
}

#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const
    ::google::protobuf::internal::ClassDataFull Lyric_class_data_ =
        Lyric::InternalGenerateClassData_(Lyric_globals_._default);

PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Lyric::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Lyric_class_data_);
  ::google::protobuf::internal::PrefetchToLocalCache(Lyric_class_data_.tc_table);
  return Lyric_class_data_.base();
}
#else
PROTOBUF_ATTRIBUTE_WEAK const ::google::protobuf::internal::ClassData* PROTOBUF_NONNULL
Lyric::GetClassData() const {
  ::google::protobuf::internal::PrefetchToLocalCache(&Lyric_globals_);
  ::google::protobuf::internal::PrefetchToLocalCache(
      ::google::protobuf::internal::MessageGlobalsBase::ToParseTableBase(&Lyric_globals_));
  return Lyric_globals_.GetClassData();
}
#endif  // !PROTOBUF_MESSAGE_GLOBALS
#ifndef PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_CONSTINIT
PROTOBUF_ATTRIBUTE_INIT_PRIORITY1 const Lyric::ParseTableT_
    Lyric::_table_ =
        Lyric::InternalGenerateParseTable_(Lyric_class_data_.base());
#endif  // !PROTOBUF_MESSAGE_GLOBALS
PROTOBUF_NOINLINE void Lyric::Clear() {
// @@protoc_insertion_point(message_clear_start:lyric.storage.Lyric)
  ::google::protobuf::internal::TSanWrite(&_impl_);
  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void) cached_has_bits;

  cached_has_bits = _impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000000fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _impl_.agents_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _impl_.lines_.Clear();
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      _impl_.version_.ClearNonDefaultToEmpty();
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(_impl_.meta_ != nullptr);
      _impl_.meta_->Clear();
    }
  }
  if (BatchCheckHasBit(cached_has_bits, 0x00000030U)) {
    _impl_.timing_ = 0;
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _impl_.extra_.Clear();
    }
  }
  _impl_._has_bits_.Clear();
  _internal_metadata_.Clear<::google::protobuf::UnknownFieldSet>();
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::uint8_t* PROTOBUF_NONNULL Lyric::_InternalSerialize(
    const ::google::protobuf::MessageLite& base, ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) {
  const Lyric& this_ = static_cast<const Lyric&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::uint8_t* PROTOBUF_NONNULL Lyric::_InternalSerialize(
    ::uint8_t* PROTOBUF_NONNULL target,
    ::google::protobuf::io::EpsCopyOutputStream* PROTOBUF_NONNULL stream) const {
  const Lyric& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    this_.CheckHasBitConsistency();
  }
  // @@protoc_insertion_point(serialize_to_array_start:lyric.storage.Lyric)
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = this_._impl_._has_bits_[0];
  // string version = 1 [json_name = "version"];
  if (CheckHasBit(cached_has_bits, 0x00000004U)) {
    if (!this_._internal_version().empty()) {
      const ::std::string& _s = this_._internal_version();
      ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
          _s.data(), static_cast<int>(_s.length()), ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.Lyric.version");
      target = stream->WriteStringMaybeAliased(1, _s, target);
    }
  }

  // .lyric.common.Timing timing = 2 [json_name = "timing"];
  if (CheckHasBit(cached_has_bits, 0x00000010U)) {
    if (this_._internal_timing() != 0) {
      target = stream->EnsureSpace(target);
      target = ::_pbi::WireFormatLite::WriteEnumToArray(
          2, this_._internal_timing(), target);
    }
  }

  // map<string, string> extra = 3 [json_name = "extra"];
  if (CheckHasBit(cached_has_bits, 0x00000020U)) {
    if (!this_._internal_extra().empty()) {
      using MapType = ::google::protobuf::Map<::std::string, ::std::string>;
      using WireHelper = _pbi::MapEntryFuncs<::std::string, ::std::string,
                                     _pbi::WireFormatLite::TYPE_STRING,
                                     _pbi::WireFormatLite::TYPE_STRING>;
      const auto& field = this_._internal_extra();

      if (stream->IsSerializationDeterministic() && field.size() > 1) {
        for (const auto& entry : ::google::protobuf::internal::MapSorterPtr<MapType>(field)) {
          target = WireHelper::InternalSerialize(
              3, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.Lyric.extra");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.Lyric.extra");
        }
      } else {
        for (const auto& entry : field) {
          target = WireHelper::InternalSerialize(
              3, entry.first, entry.second, target, stream);
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.first.data(), static_cast<int>(entry.first.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.Lyric.extra");
          ::google::protobuf::internal::WireFormatLite::VerifyUtf8String(
              entry.second.data(), static_cast<int>(entry.second.length()),
 ::google::protobuf::internal::WireFormatLite::SERIALIZE, "lyric.storage.Lyric.extra");
        }
      }
    }
  }

  // .lyric.common.Meta meta = 4 [json_name = "meta"];
  if (CheckHasBit(cached_has_bits, 0x00000008U)) {
    target = ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
        4, *this_._impl_.meta_, this_._impl_.meta_->GetCachedSize(), target,
        stream);
  }

  // repeated .lyric.common.AgentItem agents = 5 [json_name = "agents"];
  if (CheckHasBit(cached_has_bits, 0x00000001U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_agents_size());
         i < n; i++) {
      const auto& repfield = this_._internal_agents().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              5, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  // repeated .lyric.storage.Line lines = 6 [json_name = "lines"];
  if (CheckHasBit(cached_has_bits, 0x00000002U)) {
    for (unsigned i = 0, n = static_cast<unsigned>(
                             this_._internal_lines_size());
         i < n; i++) {
      const auto& repfield = this_._internal_lines().Get(i);
      target =
          ::google::protobuf::internal::WireFormatLite::InternalWriteMessage(
              6, repfield, repfield.GetCachedSize(),
              target, stream);
    }
  }

  if (ABSL_PREDICT_FALSE(this_._internal_metadata_.have_unknown_fields())) {
    target =
        ::_pbi::WireFormat::InternalSerializeUnknownFieldsToArray(
            this_._internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance), target, stream);
  }
  // @@protoc_insertion_point(serialize_to_array_end:lyric.storage.Lyric)
  return target;
}

#if defined(PROTOBUF_CUSTOM_VTABLE)
::size_t Lyric::ByteSizeLong(const MessageLite& base) {
  const Lyric& this_ = static_cast<const Lyric&>(base);
#else   // PROTOBUF_CUSTOM_VTABLE
::size_t Lyric::ByteSizeLong() const {
  const Lyric& this_ = *this;
#endif  // PROTOBUF_CUSTOM_VTABLE
  // @@protoc_insertion_point(message_byte_size_start:lyric.storage.Lyric)
  ::size_t total_size = 0;

  ::uint32_t cached_has_bits = 0;
  // Prevent compiler warnings about cached_has_bits being unused
  (void)cached_has_bits;

  ::_pbi::Prefetch5LinesFrom7Lines(&this_);
  cached_has_bits = this_._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    // repeated .lyric.common.AgentItem agents = 5 [json_name = "agents"];
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      total_size += 1UL * this_._internal_agents_size();
      for (const auto& msg : this_._internal_agents()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // repeated .lyric.storage.Line lines = 6 [json_name = "lines"];
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      total_size += 1UL * this_._internal_lines_size();
      for (const auto& msg : this_._internal_lines()) {
        total_size += ::google::protobuf::internal::WireFormatLite::MessageSize(msg);
      }
    }
    // string version = 1 [json_name = "version"];
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!this_._internal_version().empty()) {
        total_size += 1 + ::google::protobuf::internal::WireFormatLite::StringSize(
                                        this_._internal_version());
      }
    }
    // .lyric.common.Meta meta = 4 [json_name = "meta"];
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      total_size += 1 +
                    ::google::protobuf::internal::WireFormatLite::MessageSize(*this_._impl_.meta_);
    }
    // .lyric.common.Timing timing = 2 [json_name = "timing"];
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (this_._internal_timing() != 0) {
        total_size += 1 +
                      ::_pbi::WireFormatLite::EnumSize(this_._internal_timing());
      }
    }
    // map<string, string> extra = 3 [json_name = "extra"];
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      total_size +=
          1 * ::google::protobuf::internal::FromIntSize(this_._internal_extra_size());
      for (const auto& entry : this_._internal_extra()) {
        total_size += _pbi::MapEntryFuncs<::std::string, ::std::string,
                                       _pbi::WireFormatLite::TYPE_STRING,
                                       _pbi::WireFormatLite::TYPE_STRING>::ByteSizeLong(entry.first, entry.second);
      }
    }
  }
  return this_.MaybeComputeUnknownFieldsSize(total_size,
                                             &this_._impl_._cached_size_);
}

void Lyric::MergeImpl(::google::protobuf::MessageLite& to_msg,
                      const ::google::protobuf::MessageLite& from_msg) {
   auto* const _this = static_cast<Lyric*>(&to_msg);
  auto& from = static_cast<const Lyric&>(from_msg);
  if constexpr (::_pbi::DebugHardenCheckHasBitConsistency()) {
    from.CheckHasBitConsistency();
  }
  ::google::protobuf::Arena* arena = _this->GetArena();
  // @@protoc_insertion_point(class_specific_merge_from_start:lyric.storage.Lyric)
  ABSL_DCHECK_NE(&from, _this);
  ::uint32_t cached_has_bits = 0;
  (void)cached_has_bits;

  cached_has_bits = from._impl_._has_bits_[0];
  if (BatchCheckHasBit(cached_has_bits, 0x0000003fU)) {
    if (CheckHasBit(cached_has_bits, 0x00000001U)) {
      _this->_internal_mutable_agents()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_agents());
    }
    if (CheckHasBit(cached_has_bits, 0x00000002U)) {
      _this->_internal_mutable_lines()->InternalMergeFromWithArena(
          ::google::protobuf::MessageLite::internal_visibility(), arena,
          from._internal_lines());
    }
    if (CheckHasBit(cached_has_bits, 0x00000004U)) {
      if (!from._internal_version().empty()) {
        _this->_internal_set_version(from._internal_version());
      } else {
        if (_this->_impl_.version_.IsDefault()) {
          _this->_internal_set_version("");
        }
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000008U)) {
      ABSL_DCHECK(from._impl_.meta_ != nullptr);
      if (_this->_impl_.meta_ == nullptr) {
        _this->_impl_.meta_ = ::google::protobuf::Message::CopyConstruct(arena, *from._impl_.meta_);
      } else {
        _this->_impl_.meta_->MergeFrom(*from._impl_.meta_);
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000010U)) {
      if (from._internal_timing() != 0) {
        _this->_impl_.timing_ = from._impl_.timing_;
      }
    }
    if (CheckHasBit(cached_has_bits, 0x00000020U)) {
      _this->_impl_.extra_.MergeFrom(from._impl_.extra_);
    }
  }
  _this->_impl_._has_bits_[0] |= cached_has_bits;
  _this->_internal_metadata_.MergeFrom<::google::protobuf::UnknownFieldSet>(
      from._internal_metadata_);
}

void Lyric::CopyFrom(const Lyric& from) {
  // @@protoc_insertion_point(class_specific_copy_from_start:lyric.storage.Lyric)
  if (&from == this) return;
  Clear();
  MergeFrom(from);
}


void Lyric::InternalSwap(Lyric* PROTOBUF_RESTRICT PROTOBUF_NONNULL other) {
  using ::std::swap;
  auto* arena = GetArena();
  ABSL_DCHECK_EQ(arena, other->GetArena());
  _internal_metadata_.InternalSwap(&other->_internal_metadata_);
  swap(_impl_._has_bits_[0], other->_impl_._has_bits_[0]);
  _impl_.agents_.InternalSwap(&other->_impl_.agents_);
  _impl_.lines_.InternalSwap(&other->_impl_.lines_);
  ::_pbi::ArenaStringPtr::InternalSwap(&_impl_.version_, &other->_impl_.version_, arena);
  ::google::protobuf::internal::memswap<
      PROTOBUF_FIELD_OFFSET(Lyric, _impl_.timing_)
      + sizeof(Lyric::_impl_.timing_)
      - PROTOBUF_FIELD_OFFSET(Lyric, _impl_.meta_)>(
          reinterpret_cast<char*>(&_impl_.meta_),
          reinterpret_cast<char*>(&other->_impl_.meta_));
  _impl_.extra_.InternalSwap(&other->_impl_.extra_);
}

::google::protobuf::Metadata Lyric::GetMetadata() const {
  return ::google::protobuf::Message::GetMetadataImpl(GetClassData()->full());
}
// @@protoc_insertion_point(namespace_scope)
}  // namespace storage
}  // namespace lyric
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google
// @@protoc_insertion_point(global_scope)
PROTOBUF_ATTRIBUTE_INIT_PRIORITY2 static ::std::false_type
    _static_init2_ [[maybe_unused]] =
        (::_pbi::AddDescriptors(&descriptor_table_storage_2flyric_2eproto),
         ::std::false_type{});
#include "google/protobuf/port_undef.inc"
