// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: storage/line.proto

#ifndef MUSIC_LYRIC_MODEL_STORAGE_LINE_GEN_H_
#define MUSIC_LYRIC_MODEL_STORAGE_LINE_GEN_H_

#include <optional>
#include <string>
#include <unordered_map>
#include <vector>

#include "model/common/line.gen.h"
#include "model/common/part.gen.h"
#include "model/common/time.gen.h"
#include "model/common/word.gen.h"

namespace music_lyric_model::storage {
	/**
	 * Background vocal line attached to a normal line.
	 * Fields mirror parsed.LineBackground (same names and order) minus `languages`.
	 */
	struct LineBackground {
		/**
		 * Line-level format-specific data with no typed field.
		 */
		std::unordered_map<std::string, std::string> extra;
		/**
		 * Time range of this background line.
		 */
		std::optional<music_lyric_model::common::Time> time;
		/**
		 * Identifiers of the performing agents.
		 * Multiple ids mean known agents performing together; a named ensemble should be a single GROUP agent instead.
		 */
		std::vector<std::string> agents;
		/**
		 * Words composing the line in order.
		 */
		std::vector<music_lyric_model::common::Word> words;
		/**
		 * Annotations applied to the whole line.
		 */
		std::optional<music_lyric_model::common::LineAnnotation> annotation;
	};

	/**
	 * Primary lyric line.
	 * Fields mirror parsed.LineNormal (same names and order) minus `languages`.
	 */
	struct Line {
		/**
		 * Line-level format-specific data with no typed field.
		 */
		std::unordered_map<std::string, std::string> extra;
		/**
		 * Time range of the line.
		 */
		std::optional<music_lyric_model::common::Time> time;
		/**
		 * Part this line belongs to.
		 */
		std::optional<music_lyric_model::common::Part> part;
		/**
		 * Identifiers of the performing agents.
		 * Multiple ids mean known agents performing together; a named ensemble should be a single GROUP agent instead.
		 */
		std::vector<std::string> agents;
		/**
		 * Words composing the line in order.
		 */
		std::vector<music_lyric_model::common::Word> words;
		/**
		 * Annotations applied to the whole line.
		 */
		std::optional<music_lyric_model::common::LineAnnotation> annotation;
		/**
		 * Background lines attached to this line.
		 */
		std::vector<LineBackground> backgrounds;
	};
} // namespace music_lyric_model::storage

#endif
