// Code generated by protoc-gen-music-lyric-cpp. DO NOT EDIT.
// source: storage/lyric.proto

#ifndef MUSIC_LYRIC_MODEL_STORAGE_LYRIC_GEN_H_
#define MUSIC_LYRIC_MODEL_STORAGE_LYRIC_GEN_H_

#include <string>
#include <unordered_map>
#include <vector>

#include "model/common/agent.gen.h"
#include "model/common/meta.gen.h"
#include "model/common/timing.gen.h"
#include "model/storage/line.gen.h"

namespace music_lyric_model::storage {
	struct Lyric {
		/**
		 * Schema version of this data model, formatted as MAJOR.MINOR.PATCH.
		 * Consumers sharing the same major version can read each other's output.
		 * Packages are unversioned; major upgrades are not guaranteed to coexist in one process.
		 */
		std::string version;
		/**
		 * Declared timing precision.
		 */
		music_lyric_model::common::Timing timing = music_lyric_model::common::Timing::Unspecified;
		/**
		 * File-level format-specific data with no typed field.
		 */
		std::unordered_map<std::string, std::string> extra;
		/**
		 * Metadata of the lyric.
		 */
		music_lyric_model::common::Meta meta;
		/**
		 * Performing agents referenced by lines.
		 */
		std::vector<music_lyric_model::common::AgentItem> agents;
		/**
		 * Lyric lines in order.
		 */
		std::vector<Line> lines;
	};
} // namespace music_lyric_model::storage

#endif
